<div class="col-md-12">
  <div class=" titleIdent"> 
      <h2  class="col-md-10">Alterar Submenu</h2><span class="closed_acao col-md-2"><i class="pg-close_line pull-right"></i></span>
    <br>
  </div>
  <div class="panel panel-default"> 
    <div class="panel-header">
    <br>
    </div>
    <div class="panel-body">
      <div class="form-group form-group-default required">
        <label>Nome</label>
        <input type="text" id="smenu_nome" class="form-control" value="<?php echo utf8_decode($view_menu_lista_alt[0]['D008_DescriCategoria']) ?>"  required>
      </div>
      <div class="form-group form-group-default">
        <label>Link</label>
        <input type="text" id="smenu_link" class="form-control" value="<?php echo str_replace("|", "/", utf8_decode($view_menu_lista_alt[0]['D008_Link'])) ?>" >
      </div>      
      <div class="row">
        <div class="col-sm-6">
          <div class="form-group form-group-default">
            <label>Ordem</label>
            <input type="text" id="smenu_ordem" class="form-control" value="<?php echo utf8_decode($view_menu_lista_alt[0]['D008_Ordem']) ?>" >
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-group form-group-default styleradio">
            <div class="input-group">
              <div class="btn-group" data-toggle="buttons">
                <label class="col-sm-3 pull-left">Status</label>
                <div class="btn-group col-sm-9 pull-right" data-toggle="buttons">
                  
                  <?php 
                    if($view_menu_lista_alt[0]['D008_Tipo'] == "_self"):
                      $checked1 = "checked";
                      $checked2 = "";
                      $active1 = "active";
                      $active2 = "";
                    elseif($view_menu_lista_alt[0]['D008_Tipo'] == "_blank"):
                      $checked1 = "";
                      $checked2 = "checked";
                      $active1 = "";
                      $active2 = "active";
                    endif;
                  ?>
                  <label class="btn btn-primary <?php echo $active1; ?>">
                    <input type="radio" name="smenu_tipo" id="option1" autocomplete="off" value="_self" <?php echo $checked1; ?>> ATIVO
                  </label>
                  <label class="btn btn-primary <?php echo $active2; ?>">
                    <input type="radio" name="smenu_tipo" id="option2" autocomplete="off"  value="_blank"  <?php echo $checked2; ?> > INATIVO
                  </label>
                </div>
              </div>
             </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class=" titleIdent"> 
      <span id="retorno" class="col-md-10"></span><a name="bt_smenu_alterar" id="bt_smenu_alterar"  href="javascript:(0)" class="btn btn-primary col-md-2">Alterar</a>
    <br>
  </div>
</div>
<div id="ref" class='clearfix'></div>