<router base="tipo/alterar">

<input type="hidden" id="code" value="<?php echo $view_tipo_lista_alt[0]['tipo_id'];?>">
<?php $config = unserialize (CONFIG_DB); ?>
<input type="hidden" id="dominio" value="<?php echo $config[0]['D001_Site'];?>">
<header class="page-header">
    <h2><?php echo translate("Tipos"); ?></h2>
    <div class="right-wrapper text-right">
        <?php $LANGUAGE_DEFAULT = unserialize(LANGUAGE_DEFAULT); ?>
        <?php $LANGUAGE_LIST = unserialize(LANGUAGE_LIST); ?>
        
        <a name="bt_tipo_alterar" id="bt_tipo_alterar" href="javascript:void(0);" class="mb-1 mt-3 mr-1 btn btn-xs btn-primary"><strong><?php echo translate("Gravar"); ?></strong></a>
        <a href="/backend/tipo/listar/lang/<?php echo $LANGUAGE_DEFAULT[0]; ?>" class="mb-1 mt-3 mr-1 ml-1 btn btn-xs btn-default"><strong><?php echo translate("Voltar"); ?></strong></a>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>
    </div>
</header>
<!-- start: Homee -->
<section class="card">
    <div class="card-body">
        <div class="invoice">
            <header class="clearfix">
              <div class="row">
                  <div class="col-sm-6 mt-3">
                      <h2 class="h2 mt-0 mb-4 text-dark font-weight-bold"><?php echo translate("Alterar Tipo"); ?></h2>
                  </div>
                  <div class="col-sm-6 mt-3">
                      <div class="m-0 mb-4 pull-right">
                        <i class="flag-icon flag-icon-<?php echo $icon; ?>" style="font-size: 24px;"></i>
                      </div>
                  </div>
              </div>
            </header>
            <div class="row">
              <div class="col-md-8">
                <section class="card mb-4">
                  <header class="card-header">
                    <h2 class="card-title pull-left"><?php echo translate("Informações Principais"); ?></h2>
                  </header>
                  <div class="card-body">
                    <form class="form-horizontal form-bordered" method="post">
                      <div class="form-group row">
                        <label class="col-lg-3 control-label text-lg-right pt-2" for="titulo"><?php echo translate("Título"); ?></label>
                        <div class="col-lg-9">
                          <input type="text" id="titulo" class="form-control" value="<?php echo $view_tipo_lista_alt[0]['tipo_nome'] ?>">
                        </div>
                      </div>    

                      <div class="form-group row">
                        <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault"><?php echo translate("Status"); ?></label>
                        <div class="col-lg-6">

                          <div class="btn-group" data-toggle="buttons">
                            <?php 
                              if($view_tipo_lista_alt[0]['tipo_status'] == "sim"):
                                $checked1 = "checked";
                                $checked2 = "";
                                $active1 = "active";
                                $active2 = "";
                              elseif($view_tipo_lista_alt[0]['tipo_status'] == "nao"):
                                $checked1 = "";
                                $checked2 = "checked";
                                $active1 = "";
                                $active2 = "active";
                              endif;
                            ?>
                            <label class="btn btn-primary <?php echo $active1; ?>" aria-pressed="true">
                              <input type="radio" name="tipo_status" id="option1" value="sim" <?php echo $checked1; ?>> <?php echo translate("Ativo"); ?>
                            </label>
                            <label class="btn btn-primary <?php echo $active2; ?>" aria-pressed="true">
                              <input type="radio" name="tipo_status" id="option2" value="nao"  <?php echo $checked2; ?>> <?php echo translate("Inativo"); ?>
                            </label>

                          </div>
                        </div>
                      </div> 

                   
                    </form>
                  </div>
                </section>
              </div>
            </div>

            <div id="ref" class='clearfix'></div>
            <span id="retorno" class="col-md-10"></span>
            <a name="bt_tipo_alterar" id="bt_tipo_alterar"  href="javascript:void(0);" class="btn btn-primary col-md-2 pull-right"><?php echo translate("Gravar"); ?></a>

        </div>
    </div>
</section>