<router base="configuracao/empresa">
<?php $languageLIST = unserialize (LANGUAGE_LIST); ?>

<header class="page-header">
    <h2>Configuração</h2>

    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Home</span></li>
            <li><span>Configuração</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>
    </div>
</header>


<!-- start: page -->
<section class="content-with-menu content-with-menu-has-toolbar media-gallery">
    <div class="content-with-menu-container">
        <div class="inner-menu-toggle">
            <a href="#" class="inner-menu-expand" data-open="inner-menu">
                Show Bar <i class="fa fa-chevron-right"></i>
            </a>
        </div>
        
        <menu id="content-menu" class="inner-menu" role="menu">
            <div class="nano">
                <div class="nano-content">
        
                    <div class="inner-menu-toggle-inside">
                        <a href="#" class="inner-menu-collapse">
                            <i class="fa fa-chevron-up visible-xs-inline"></i><i class="fa fa-chevron-left hidden-xs-inline"></i> Hide Bar
                        </a>
                        <a href="#" class="inner-menu-expand" data-open="inner-menu">
                            Show Bar <i class="fa fa-chevron-down"></i>
                        </a>
                    </div>
        
                    <div class="inner-menu-content">
          
                        <div class="sidebar-widget m-0">
                            <div class="widget-header clearfix">
                                <h6 class="title float-left mt-1">MENU</h6>
                         <!--        <div class="float-right">
                                    <a href="/backend/idioma/registar" class="btn btn-dark btn-sm btn-widget-act">TESTE</a>
                                </div> -->
                            </div>

                            <!-- config navigation menu -->
                            <?php include_once("partials/nav-config-menu.phtml") ?>
                            <!-- /config navigation menu -->

                        </div>        
                    </div>
                </div>
            </div>
        </menu>
        <div class="inner-body mg-main">
        
            <div class="inner-toolbar clearfix">
                <ul>
                    <li class="col-md-12 pb-3">
                        <h3 class="mt-0 mb-0 text-light font-weight-bold pull-left">Dados da Empresa</h3>
                        <a name="bt_cfg" id="bt_cfg" href="javascript:;" class="btn text-light btn-primary btn-sm btn-widget-act pull-right mt-0 mb-4" style="margin-top: -5px!important;">Guardar</a>
                    </li>
                </ul>
            </div>
            <div class="row mg-files" data-sort-destination data-sort-id="media-gallery">
              <section class="card">
                <div class="card-body">
                    <div class="invoice" style="padding-bottom: 150px;">     
                        <div class="row">
                          <div class="col-md-8">
                            <section class="card mb-4">
                              <header class="card-header">
                                <h2 class="card-title">Informações</h2>
                              </header>
                              <div class="card-body">
                                <form class="form-horizontal form-bordered" method="post">

                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Empresa</label>
                                    <div class="col-lg-9">
                                      <input type="text" id="cfg_empresa" class="form-control" value="<?php echo $view_config_lista[0]['D001_Empresa']; ?>">
                                    </div>
                                  </div>

                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="cfg_cp">CP</label>
                                    <div class="col-lg-9">
                                      <input type="text" id="cfg_cp" class="form-control" value="<?php echo utf8_decode($view_config_lista[0]['D001_Cp']) ?>">
                                    </div>
                                  </div>
                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="cfg_morada">Morada</label>
                                    <div class="col-lg-9">
                                      <input type="text" id="cfg_morada" class="form-control" value="<?php echo $view_config_lista[0]['D001_Morada']; ?>">
                                    </div>
                                  </div>
                                  
                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="cfg_localidade">Localidade</label>
                                    <div class="col-lg-9">
                                      <input type="text" id="cfg_localidade" class="form-control" value="<?php echo $view_config_lista[0]['D001_Cidade']; ?>">
                                    </div>
                                  </div>                 
                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="cfg_distrito">Estado</label>
                                    <div class="col-lg-9">
                                      <input type="text" id="cfg_distrito" class="form-control" value="<?php echo $view_config_lista[0]['D001_Distrito']; ?>">
                                    </div>
                                  </div>


                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Telefone</label>
                                    <div class="col-lg-9">
                                      <div class="input-group">
                                        <span class="input-group-addon">
                                          <i class="fa fa-phone"></i>
                                        </span>
                                        <input id="cfg_telefone" value="<?php echo implode('/', array_reverse(explode('-', $view_config_lista[0]['D001_Telefone']))) ?>" type="text" class="form-control">
                                      </div>
                                    </div>
                                  </div>  

                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Email</label>
                                    <div class="col-lg-9">
                                      <div class="input-group">
                                        <span class="input-group-addon">
                                          <i class="fa fa-envelope"></i>
                                        </span>
                                        <input type="text" id="cfg_email" class="form-control" value="<?php echo $view_config_lista[0]['D001_Email']; ?>">
                                      </div>
                                    </div>
                                  </div>

                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Website</label>
                                    <div class="col-lg-9">
                                      <div class="input-group">
                                        <span class="input-group-addon">
                                          <i class="fa fa-link"></i>
                                        </span>
                                        <input type="text" id="cfg_site" class="form-control" value="<?php echo $view_config_lista[0]['D001_Site']; ?>">
                                      </div>
                                    </div>
                                  </div>

                                  <div class="form-group row">
                                    <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">MAIS INFORMAÇÕES</label>
                                    <div class="col-lg-9">
                                      <?php
                                      require_once $_SERVER['DOCUMENT_ROOT']."/backend/public/vendor/ckeditor/ckeditor.php";
                                      require_once $_SERVER['DOCUMENT_ROOT']."/backend/public/vendor/ckfinder/ckfinder.php";
                                      $CKEditor = new CKEditor();
                                      $CKEditor->basePath = '/backend/public/vendor/ckeditor/';
                                      CKFinder::SetupCKEditor($CKEditor, '/backend/public/vendor/ckfinder/'); 
                                      $initialValue = str_replace("|", "/", $view_config_lista[0]['D001_Obs']);
                                      $CKEditor->editor("cfg_obs", $initialValue);
                                    ?>
                                    </div>
                                  </div>
                      
                                   
                                </form>
                              </div>
                            </section>            
                          </div>
                          <div class="col-md-4">
                            <section class="card mb-4">
                                <header class="card-header">
                                  <h2 class="card-title">Imagens</h2>
                                </header>
                                <div class="card-body">
                   
                                  <div class="form-group row">
                                    <label class="col-sm-12 control-label text-sm-left pt-2"><strong>Favicon</strong></label>
                                    <div class="col-sm-12 media-gallery">
                                      <div id="queue" class="mt-3 mb-3"></div>
                                      <input id="cfg_favicon" name="cfg_favicon" type="file" multiple>
                                      <input type="hidden" id="timestamp" value="<?php echo $timestamp = time();?>">
                                      <input type="hidden" id="unique_salt" value="<?php echo md5('unique_salt' . $timestamp);?>"> 
                                      <input type="hidden" id="config_favicon" value="<?php echo $view_config_lista[0]['D001_Favicon'];?>"> 
                                      <span class="pull-right">tam: 256px x 256px</span>
                                      <hr class="mt-3 mb-3">
                                      <?php if(!empty($view_config_lista[0]['D001_Favicon'] )): ?>

                                      <div class="row mg-files" data-sort-destination="" data-sort-id="media-gallery" style="position: relative; height:150px;">

                                        <div class="isotope-item document col-xs-12 col-sm-5 col-md-5 col-lg-5" style="position: absolute; left: 0px; top: 5px;">
                                          <div class="thumbnail">
                                            <div class="thumb-preview">
                                              <a class="thumb-image" href="/images/config/<?php echo $view_config_lista[0]['D001_Favicon'] ?>">
                                                <img src="/images/config/<?php echo $view_config_lista[0]['D001_Favicon'] ?>" class="img-fluid" height="50" alt="favicon">
                                              </a>
                                              <div class="mg-thumb-options" style="overflow: visible;">
                                                <!-- <div class="mg-zoom"><i class="fa fa-search"></i></div> -->
                                                <div class="mg-toolbar">
                                                  <div class="mg-group float-right show">                                        
                                                    <button class="dropdown-toggle mg-toggle" data-toggle="dropdown" aria-expanded="true"><span class="caret"></span></button>
                                                    <div class="dropdown-menu mg-dropdown show" role="menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(271px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                      <a class="dropdown-item text-1" href="/images/config/<?php echo $view_config_lista[0]['D001_Favicon'] ?>" download="Imagem_favicon"><i class="fa fa-download"></i> Download</a>
                                                      <a class="dropdown-item text-1" name="img_Del" href="javascript:;" ref="D001_Favicon" ><i class="fa fa-trash-o"></i> Apagar</a>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                            <!-- <div class="mg-description">
                                              <small class="float-left text-muted">Design, Websites</small>
                                              <small class="float-right text-muted">07/10/2017</small>
                                            </div> -->
                                          </div>
                                        </div>
                                      </div>

                                      <?php endif; ?>

                                    </div> 

                                  </div> 

                                  <div class="form-group row">
                                    <label class="col-sm-12 control-label text-sm-left pt-2"><strong>Logo</strong></label>
                                    <div class="col-sm-12 media-gallery">
                                      <div id="queue2" class="mt-3 mb-3"></div>
                                      <input id="cfg_logo" name="cfg_logo" type="file" multiple>
                                      <input type="hidden" id="timestamp" value="<?php echo $timestamp = time();?>">
                                      <input type="hidden" id="unique_salt" value="<?php echo md5('unique_salt' . $timestamp);?>"> 
                                      <input type="hidden" id="config_logo" value="<?php echo $view_config_lista[0]['D001_Logosite'];?>">
                                      <span class="pull-right">tam: 350px x 200px</span>
                                      <hr class="mt-3 mb-3">
                                      <?php if(!empty($view_config_lista[0]['D001_Logosite'] )): ?>

                                      <div class="row mg-files" data-sort-destination="" data-sort-id="media-gallery" style="position: relative; height:280px;">

                                        <div class="isotope-item document col-xs-12 col-sm-12 col-md-12 col-lg-12" style="position: absolute; left: 0px; top: 5px;">
                                          <div class="thumbnail">
                                            <div class="thumb-preview">
                                              <a class="thumb-image" href="/images/config/<?php echo $view_config_lista[0]['D001_Logosite'] ?>">
                                                <img src="/images/config/<?php echo $view_config_lista[0]['D001_Logosite'] ?>" class="img-fluid" height="50" alt="logo">
                                              </a>
                                              <div class="mg-thumb-options" style="overflow: visible;">
                                                <!-- <div class="mg-zoom"><i class="fa fa-search"></i></div> -->
                                                <div class="mg-toolbar">
                                                  <div class="mg-group float-right show">                                        
                                                    <button class="dropdown-toggle mg-toggle" data-toggle="dropdown" aria-expanded="true"><span class="caret"></span></button>
                                                    <div class="dropdown-menu mg-dropdown show" role="menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(271px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                      <a class="dropdown-item text-1" href="/images/config/<?php echo $view_config_lista[0]['D001_Logosite'] ?>" download="logo"><i class="fa fa-download"></i> Download</a>
                                                      <a class="dropdown-item text-1" name="img_Del" href="javascript:;" ref="D001_Logosite" ><i class="fa fa-trash-o"></i> Apagar</a>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                            <!-- <div class="mg-description">
                                              <small class="float-left text-muted">Design, Websites</small>
                                              <small class="float-right text-muted">07/10/2017</small>
                                            </div> -->
                                          </div>
                                        </div>
                                      </div>

                                      <?php endif; ?>

                                    </div> 

                                  </div> 

                                  <div class="form-group row">
                                    <label class="col-sm-12 control-label text-sm-left pt-2"><strong>Logo Alternativo</strong></label>
                                    <div class="col-sm-12 media-gallery">
                                      <div id="queue3" class="mt-3 mb-3"></div>
                                      <input id="cfg_logo2" name="cfg_logo2" type="file" multiple>
                                      <input type="hidden" id="timestamp2" value="<?php echo $timestamp2 = time();?>">
                                      <input type="hidden" id="unique_salt2" value="<?php echo md5('unique_salt' . $timestamp2);?>"> 
                                      <input type="hidden" id="config_logoalt" value="<?php echo $view_config_lista[0]['D001_Logosite2'];?>">
                                      <span class="pull-right">tam: 350px x 200px</span>
                                      <hr class="mt-3 mb-3">
                                      <?php if(!empty($view_config_lista[0]['D001_Logosite2'] )): ?>

                                      <div class="row mg-files" data-sort-destination="" data-sort-id="media-gallery" style="position: relative; height:280px;">

                                        <div class="isotope-item document col-xs-12 col-sm-12 col-md-12 col-lg-12" style="position: absolute; left: 0px; top: 5px;">
                                          <div class="thumbnail">
                                            <div class="thumb-preview">
                                              <a class="thumb-image" href="/images/config/<?php echo $view_config_lista[0]['D001_Logosite2'] ?>">
                                                <img src="/images/config/<?php echo $view_config_lista[0]['D001_Logosite2'] ?>" class="img-fluid" height="50" alt="logo_alt">
                                              </a>
                                              <div class="mg-thumb-options" style="overflow: visible;">
                                                <!-- <div class="mg-zoom"><i class="fa fa-search"></i></div> -->
                                                <div class="mg-toolbar">
                                                  <div class="mg-group float-right show">                                        
                                                    <button class="dropdown-toggle mg-toggle" data-toggle="dropdown" aria-expanded="true"><span class="caret"></span></button>
                                                    <div class="dropdown-menu mg-dropdown show" role="menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(271px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                      <a class="dropdown-item text-1" href="/images/config/<?php echo $view_config_lista[0]['D001_Logosite2'] ?>" download="logo_alt"><i class="fa fa-download"></i> Download</a>
                                                      <a class="dropdown-item text-1" name="img_Del" href="javascript:;" ref="D001_Logosite2" ><i class="fa fa-trash-o"></i> Apagar</a>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                            <!-- <div class="mg-description">
                                              <small class="float-left text-muted">Design, Websites</small>
                                              <small class="float-right text-muted">07/10/2017</small>
                                            </div> -->
                                          </div>
                                        </div>
                                      </div>

                                      <?php endif; ?>

                                    </div> 

                                  </div> 

                                  <?php if(false): ?>
                                  <div class="form-group row">
                                    <label class="col-sm-12 control-label text-sm-left pt-2"><strong>Imagem para partilhar redes sociais (LINKS)</strong></label>
                                    <div class="col-sm-12 media-gallery">
                                      <div id="queue4" class="mt-3 mb-3"></div>
                                      <input id="cfg_logosocial" name="cfg_logosocial" type="file" multiple>
                                      <input type="hidden" id="timestamp2" value="<?php echo $timestamp2 = time();?>">
                                      <input type="hidden" id="unique_salt2" value="<?php echo md5('unique_salt' . $timestamp2);?>"> 
                                      <input type="hidden" id="config_logosocial" value="<?php echo $view_config_lista[0]['D001_Logosocial'];?>">
                                      <span class="pull-right">tam: 500px x 500px</span>
                                      <hr class="mt-3 mb-3">
                                      <?php if(!empty($view_config_lista[0]['D001_Logosocial'] )): ?>

                                      <div class="row mg-files" data-sort-destination="" data-sort-id="media-gallery" style="position: relative; height:150px;">

                                        <div class="isotope-item document col-xs-12 col-sm-12 col-md-5 col-lg-5" style="position:absolute; left: 0px; top: 5px;">
                                          <div class="thumbnail">
                                            <div class="thumb-preview">
                                              <a class="thumb-image" href="/images/config/<?php echo $view_config_lista[0]['D001_Logosocial'] ?>">
                                                <img src="/images/config/<?php echo $view_config_lista[0]['D001_Logosocial'] ?>" class="img-fluid" height="50"  alt="logo-social">
                                              </a>
                                              <div class="mg-thumb-options" style="overflow: visible;">
                                                <!-- <div class="mg-zoom"><i class="fa fa-search"></i></div> -->
                                                <div class="mg-toolbar">
                                                  <div class="mg-group float-right show">                                        
                                                    <button class="dropdown-toggle mg-toggle" data-toggle="dropdown" aria-expanded="true"><span class="caret"></span></button>
                                                    <div class="dropdown-menu mg-dropdown show" role="menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(271px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                      <a class="dropdown-item text-1" href="/images/config/<?php echo $view_config_lista[0]['D001_Logosocial'] ?>" download="logo-social"><i class="fa fa-download"></i> Download</a>
                                                      <a class="dropdown-item text-1" name="img_Del" href="javascript:;" ref="D001_Logosocial" ><i class="fa fa-trash-o"></i> Apagar</a>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                            <!-- <div class="mg-description">
                                              <small class="float-left text-muted">Design, Websites</small>
                                              <small class="float-right text-muted">07/10/2017</small>
                                            </div> -->
                                          </div>
                                        </div>
                                      </div>

                                      <?php endif; ?>

                                    </div> 

                                  </div> 
                                  


                                  <div class="form-group row">
                                    <label class="col-sm-12 control-label text-sm-left pt-2"><strong>Pino do mapa</strong></label>
                                    <div class="col-sm-12 media-gallery">
                                      <div id="queue5" class="mt-3 mb-3"></div>
                                      <input id="cfg_pino" name="cfg_pino" type="file" multiple>
                                      <input type="hidden" id="timestamp2" value="<?php echo $timestamp2 = time();?>">
                                      <input type="hidden" id="unique_salt2" value="<?php echo md5('unique_salt' . $timestamp2);?>"> 
                                      <input type="hidden" id="config_pino" value="<?php echo $view_config_lista[0]['D001_Pino'];?>">
                                      <span class="pull-right">tam: 64px x 64px</span>
                                      <hr class="mt-3 mb-3">
                                      <?php if(!empty($view_config_lista[0]['D001_Pino'] )): ?>

                                      <div class="row mg-files" data-sort-destination="" data-sort-id="media-gallery" style="position: relative; height:150px;">

                                        <div class="isotope-item document col-xs-12 col-sm-12 col-md-5 col-lg-5" style="position:absolute; left: 0px; top: 5px;">
                                          <div class="thumbnail">
                                            <div class="thumb-preview">
                                              <a class="thumb-image" href="/images/config/<?php echo $view_config_lista[0]['D001_Pino'] ?>">
                                                <img src="/images/config/<?php echo $view_config_lista[0]['D001_Pino'] ?>" class="img-fluid" height="50"  alt="pino">
                                              </a>
                                              <div class="mg-thumb-options" style="overflow: visible;">
                                                <!-- <div class="mg-zoom"><i class="fa fa-search"></i></div> -->
                                                <div class="mg-toolbar">
                                                  <div class="mg-group float-right show">                                        
                                                    <button class="dropdown-toggle mg-toggle" data-toggle="dropdown" aria-expanded="true"><span class="caret"></span></button>
                                                    <div class="dropdown-menu mg-dropdown show" role="menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(271px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                      <a class="dropdown-item text-1" href="/images/config/<?php echo $view_config_lista[0]['D001_Pino'] ?>" download="pino"><i class="fa fa-download"></i> Download</a>
                                                      <a class="dropdown-item text-1" name="img_Del" href="javascript:;" ref="D001_Pino" ><i class="fa fa-trash-o"></i> Apagar</a>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                            <!-- <div class="mg-description">
                                              <small class="float-left text-muted">Design, Websites</small>
                                              <small class="float-right text-muted">07/10/2017</small>
                                            </div> -->
                                          </div>
                                        </div>
                                      </div>

                                      <?php endif; ?>

                                    </div> 

                                  </div> 

                                  <?php endif; ?>
                                 

                                </div>
                              </section>
                            </div>
                        </div>  
                    </div>
                </div>
              </section>  
            </div>
        </div>
    </div>
</section>
<!-- end: page -->