<router base="configuracao/calendario">

<?php $languageLIST = unserialize(LANGUAGE_LIST); ?>

<header class="page-header">
    <h2><?php echo translate("Configuração"); ?></h2>

    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span><?php echo translate("Home"); ?></span></li>
            <li><span><?php echo translate("Configuração"); ?></span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>
    </div>
</header>

<!-- start: page -->
<section class="content-with-menu content-with-menu-has-toolbar media-gallery">
    <div class="content-with-menu-container">
        <div class="inner-menu-toggle">
            <a href="#" class="inner-menu-expand" data-open="inner-menu">
                Show Bar <i class="fa fa-chevron-right"></i>
            </a>
        </div>
        
        <menu id="content-menu" class="inner-menu" role="menu">
            <div class="nano">
                <div class="nano-content">
        
                    <div class="inner-menu-toggle-inside">
                        <a href="#" class="inner-menu-collapse">
                            <i class="fa fa-chevron-up visible-xs-inline"></i><i class="fa fa-chevron-left hidden-xs-inline"></i> Hide Bar
                        </a>
                        <a href="#" class="inner-menu-expand" data-open="inner-menu">
                            Show Bar <i class="fa fa-chevron-down"></i>
                        </a>
                    </div>
        
                    <div class="inner-menu-content">
          
                        <div class="sidebar-widget m-0">
                            <div class="widget-header clearfix">
                                <h6 class="title float-left mt-1"><?php echo translate("MENU"); ?></h6>
                         <!--        <div class="float-right">
                                    <a href="/backend/idioma/registar" class="btn btn-dark btn-sm btn-widget-act">TESTE</a>
                                </div> -->
                            </div>

                            <!-- config navigation menu -->
                            <?php include_once("partials/nav-config-menu.phtml") ?>
                            <!-- /config navigation menu -->

                        </div>        
                    </div>
                </div>
            </div>
        </menu>
        <div class="inner-body mg-main">
        
            <div class="inner-toolbar clearfix">
                <ul>
                    <li class="col-md-12 pb-3">
                        <h3 class="mt-0 mb-0 text-light font-weight-bold pull-left"><?php echo translate("Integração"); ?></h3>
                        <a name="bt_cfg" id="bt_cfg" href="javascript:;" class="btn text-light btn-primary btn-sm btn-widget-act pull-right mt-0 mb-4" style="margin-top: -5px!important;"><?php echo translate("Guardar"); ?></a>
                    </li>
                </ul>
            </div>
            <div class="invoice" style="padding-bottom: 150px;">     
              <div class="row">
                <div class="col-md-9">
                  <section class="card mb-4">
                    <header class="card-header">
                      <h2 class="card-title"><?php echo translate("Google Calendar"); ?></h2>
                    </header>
                    <div class="card-body">
                      <form class="form-horizontal form-bordered" method="post">

                            <div class="form-group row">
                                
                                <div class="col-lg-3 control-label text-lg-right pt-2"></div>

                                <div class="col-lg-9">
                                    <div class="google-calendar-signed-in-info"></div>
                                    <button type="button" class="btn-xs btn btn-primary" id="authorize_button" style="display: none;"><?php echo translate("Autorizar Calendário Google"); ?></button>
                                    <button type="button" class="btn btn-xs btn-primary" id="signout_button" style="display: none;"><?php echo translate("Desligar conta"); ?></button>
                                </div>

                            </div>
                          
                          <div class="form-group row">
                            <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault"><?php echo translate("Google API Key"); ?></label>
                            <div class="col-lg-9">
                                <input type="text" id="cfg_ga_api_key" class="form-control" value="<?php echo $view_config_lista[0]['D001_GA_api_key']; ?>">
                            </div>
                          </div>

                          <br />

                          <div class="form-group row">
                            <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault"><?php echo translate("Google Client Key"); ?></label>
                            <div class="col-lg-9">
                                <input type="text" id="cfg_ga_client_id" class="form-control" value="<?php echo $view_config_lista[0]['D001_GA_client_id']; ?>">
                            </div>
                          </div>

                          
                          
                      </form>
                    </div>

                  </section>            
                </div>
              </div>  
            </div>
        </div>
    </div>
</section>
<!-- end: page -->