<router base="usuario/alterar">

<input type="hidden" id="usu_idioma" value="<?php echo $view_usuario_lista_alt[0]['usu_idioma'];?>">

<header class="page-header">

    <h2><?php echo translate("Utilizador"); ?></h2>

    <div class="right-wrapper text-right">

        <?php $LANGUAGE_DEFAULT = unserialize(LANGUAGE_DEFAULT); ?>

        <a name="bt_usu_alterar" id="bt_usu_alterar" href="javascript:$('#usu_img').uploadifive('upload')" class="mb-1 mt-3 mr-1 btn btn-xs btn-primary"><strong><?php echo translate("Gravar"); ?></strong></a>

        <a href="/backend/usuario/listar/lang/<?php echo $LANGUAGE_DEFAULT[0]; ?>" class="mb-1 mt-3 mr-1 ml-1 btn btn-xs btn-default"><strong><?php echo translate("Voltar"); ?></strong></a>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>

    </div>

</header>



<!-- start: file -->



<?php //$icon = ($view_usuario_lista_alt[0]['usu_idioma'] == "en" ? "gb" : $view_usuario_lista_alt[0]['usu_idioma']); ?>



<section class="card">

    <div class="card-body">

        <div class="invoice">

            <header class="clearfix">

                <div class="row">

                    <div class="col-sm-6 mt-3">

                        <h2 class="h2 mt-0 mb-4 text-dark font-weight-bold"><?php echo translate("Alterar Utilizador"); ?></h2>

                        <!-- <h4 class="h4 m-0 text-dark font-weight-bold">#76598345</h4> -->

                    </div>

                    <div class="col-sm-6 mt-3">

                        <div class="m-0 mb-4 pull-right">

                          <i class="flag-icon flag-icon-<?php echo $icon; ?>" style="font-size: 24px;"></i>

                        </div>

                    </div>

                </div>

            </header>



            <div class="row">

              <div class="col-md-8">

                <section class="card mb-4">

                  <header class="card-header">

                    <h2 class="card-title"><?php echo translate("Principal"); ?></h2>

                  </header>

                  <div class="card-body">

                    <form class="form-horizontal form-bordered" method="post">



                      <div class="form-group row">

                        <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_nome"><?php echo translate("Nome"); ?></label>

                        <div class="col-lg-9">

                          <input type="text" id="usu_nome" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_nome'] ?>">

                        </div>

                      </div>



                      <div class="form-group row">

                        <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_funcao"><?php echo translate("Função"); ?></label>

                        <div class="col-lg-9">

                          <input type="text" id="usu_funcao" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_funcao'] ?>">

                        </div>

                      </div>

            

                      <div class="form-group row">

                        <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_texto"><?php echo translate("Observação"); ?></label>

                        <div class="col-lg-9">                        

                          <!-- <textarea class="form-control" name="fil_texto" id="fil_texto"></textarea> -->

                          <?php

                            require_once $_SERVER['DOCUMENT_ROOT']."/backend/public/vendor/ckeditor/ckeditor.php";

                            require_once $_SERVER['DOCUMENT_ROOT']."/backend/public/vendor/ckfinder/ckfinder.php";

                            

                            $initialValue = str_replace("|", "/", $view_usuario_lista_alt[0]['usu_texto']);

                            $CKEditor = new CKEditor();

                            $CKEditor->basePath = '/backend/public/vendor/ckeditor/';

                            CKFinder::SetupCKEditor($CKEditor, '/backend/vendor/plugins/ckfinder/');

                            $CKEditor->editor("usu_texto", $initialValue);

                          ?>

                        </div>

                      </div>

                   

                      <div class="form-group row">

             

                        <label class="col-sm-3 control-label text-sm-right pt-2"><?php echo translate("Status"); ?></label>

                        <div class="btn-group col-sm-9 pull-right" data-toggle="buttons">

                       

                            <?php 

                            if($view_usuario_lista_alt[0]['usu_status'] == "Sim"):

                              $checked1 = "checked";

                              $checked2 = "";

                              $active1 = "active";

                              $active2 = "";

                            elseif($view_usuario_lista_alt[0]['usu_status'] == "Nao"):

                              $checked1 = "";

                              $checked2 = "checked";

                              $active1 = "";

                              $active2 = "active";

                            endif;

                          ?>

                          <label class="btn btn-primary <?php echo $active1; ?>">

                            <input type="radio" name="usu_status" id="option1" autocomplete="off" value="Sim" <?php echo $checked1; ?>> <?php echo translate("Sim"); ?>

                          </label>

                          <label class="btn btn-primary <?php echo $active2; ?>">

                            <input type="radio" name="usu_status" id="option2" autocomplete="off"  value="Nao"  <?php echo $checked2; ?>> <?php echo translate("Não"); ?>

                          </label>

                        </div>



                      </div>

                         

                    </form>

                  </div>



                  <header class="card-header">

                    <h2 class="card-title"><?php echo translate("Localização"); ?></h2>

                  </header>

                  <div class="card-body">



                    <div class="form-group row">

                      <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_morada"><?php echo translate("Morada"); ?></label>

                      <div class="col-lg-9">

                        <input type="text" id="usu_morada" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_morada'] ?>">

                      </div>

                    </div>



                    <div class="form-group row">

                      <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_localidade"><?php echo translate("Localidade"); ?></label>

                      <div class="col-lg-9">

                        <input type="text" id="usu_localidade" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_localidade'] ?>">

                      </div>

                    </div>



                    <div class="form-group row">

                      <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_distrito"><?php echo translate("Distrito"); ?></label>

                      <div class="col-lg-9">

                        <input type="text" id="usu_distrito" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_distrito'] ?>">

                      </div>

                    </div>



                    <div class="form-group row">

                      <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_cp"><?php echo translate("CP"); ?></label>

                      <div class="col-lg-9">

                        <input type="text" id="usu_cp" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_cp'] ?>">

                      </div>

                    </div>

                

                  </div>



                  <header class="card-header">

                    <h2 class="card-title"><?php echo translate("Contactos"); ?></h2>

                  </header>

                  <div class="card-body">



                    <div class="form-group row">

                      <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_telefone"><?php echo translate("Telefone"); ?></label>

                      <div class="col-lg-9">

                        <input type="text" id="usu_telefone" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_telefone'] ?>">

                      </div>

                    </div>

                    <div class="form-group row">

                      <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_telemovel"><?php echo translate("Telemóvel"); ?></label>

                      <div class="col-lg-9">

                        <input type="text" id="usu_telemovel" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_telemovel'] ?>">

                      </div>

                    </div>

                    <div class="form-group row">

                      <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_email"><?php echo translate("Email"); ?></label>

                      <div class="col-lg-9">

                        <input type="text" id="usu_email" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_email'] ?>">

                      </div>

                    </div>

                    <div class="form-group row">

                      <label class="col-lg-3 control-label text-lg-right pt-2" for="usu_website"><?php echo translate("Website"); ?></label>

                      <div class="col-lg-9">

                        <input type="text" id="usu_website" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_website'] ?>">

                      </div>

                    </div>

                  

                  </div> 



                </section>



              </div>

              <div class="col-md-4">

                <section class="card mb-4">

                    <header class="card-header">

                      <h2 class="card-title"><?php echo translate("Dados de acesso"); ?></h2>

                    </header>

                    <div class="card-body">


                      <div class="form-group row">

                          <label class="col-lg-12 control-label text-lg-left pt-2"><?php echo translate("Email"); ?></label>

                          <div class="col-lg-12">

                            <input type="text" id="usu_login" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_login'] ?>">

                          </div>

                      </div>

                      <div class="form-group row">

                          <label class="col-lg-12 control-label text-lg-left pt-2"><?php echo translate("Senha"); ?></label>

                          <div class="col-lg-12">

                            <input type="password" id="usu_senha" class="form-control">

                          </div>

                      </div>  

                      <div class="form-group row">

                          <label class="col-lg-12 control-label text-lg-left pt-2"><?php echo translate("Confirmação Senha"); ?></label>

                          <div class="col-lg-12">

                            <input type="password" id="usu_confsenha" class="form-control">

                            <span id="msgSenha" class="obg" style="padding-left:3px; padding-top:5px;"></span>

                          </div>

                      </div>   



                      <div class="form-group row">

                        

                        <label class="col-sm-12 control-label text-sm-left pt-2"><?php echo translate("Nível"); ?></label>

                        <div class="col-lg-12"> 

                          <select id="usu_nivel" class="form-control">

                            <option value="0"><?php echo translate("SELECIONE"); ?></option>

                            <?php

                              if(!empty($view_usuario_nivel)):

                                  foreach ($view_usuario_nivel as $nivel):

                                    if($view_usuario_lista_alt[0]['niv_id'] == $nivel['niv_id'] ){

                                      $selected = "selected"; 

                                      echo  '<option value="'.$nivel['niv_id'].'" '.$selected.'>'.$nivel['niv_nome'].'</option>';

                                    }elseif($view_usuario_lista_alt[0]['niv_id'] != $nivel['niv_id']){

                                      echo  '<option value="'.$nivel['niv_id'].'" >'.$nivel['niv_nome'].'</option>';

                                    }

                                  endforeach;

                              endif; ?>

                          </select>

                        </div>

                      </div>   

          

                      <hr>

                      <!-- calendar id -->
                    <div class="form-group row">

                    <label class="col-lg-12 control-label text-lg-left pt-2"><?php echo translate("Calendário Google (ID)"); ?></label>

                    <div class="col-lg-12">

                      <input type="text" id="usu_calendar_id" class="form-control" value="<?php echo $view_usuario_lista_alt[0]['usu_calendar_id'] ?>">

                    </div>

                    </div>
                    <!-- /calendar id -->



                      <!--div class="form-group row">

                        <h5 class="control-label text-sm-right pt-2">Tipo de Página</h5>

                        <select id="usu_controller" class="form-control" required disabled>

                        <option value="0"></option> 

                        <?php

                        if(isset($view_modulo) && false):

                            foreach ($view_modulo as $modulo): 

                              if($view_usuario_lista_alt[0]['usu_controle'] == $modulo["mod_modulo"] ){

                                $selected = "selected"; 

                                echo  '<option value="'.$modulo["mod_modulo"].'" '.$selected.'>'.$modulo["mod_titulo"].'</option>';

                              }elseif($view_usuario_lista_alt[0]['usu_controle'] != $modulo["mod_modulo"]){

                                echo  '<option value="'.$modulo["mod_modulo"].'" >'.$modulo["mod_titulo"].'</option>';

                              }

                            endforeach;

                        endif; ?>

                        </select>

                      </div--> 



                      <hr>



                      <div class="form-group row">

    

                        <label class="col-sm-12 control-label text-sm-right pt-2"><?php echo translate("Imagem"); ?></label>

                        <div class="col-sm-12 media-gallery">

                          <div id="queue" class="mt-3 mb-3"></div>

                          <input id="usu_img" name="usu_img" type="file" multiple>

                          <input type="hidden" id="timestamp" value="<?php echo $timestamp = time();?>">

                          <input type="hidden" id="unique_salt" value="<?php echo md5('unique_salt' . $timestamp);?>">      

                          <input type="hidden" id="usu_code" value="<?php echo $view_usuario_lista_alt[0]['usu_id'];?>">                   

                          <!-- <span class="pull-right">tam: 1920px x 480px</span> -->



                          <hr class="mt-3 mb-3">

                          <?php if(!empty($view_usuario_lista_alt[0]['usu_foto'] )): ?>



                          <div class="row mg-files" data-sort-destination="" data-sort-id="media-gallery" style="position: relative; height:400px;">



                            <div class="isotope-item document col-xs-12 col-sm-11 col-md-11 col-lg-11" style="position: relative; left: 0px; top: 5px;">

                              <div class="thumbnail">

                                <div class="thumb-preview">

                                  <a class="thumb-image" href="/images/usuario/<?php echo $view_usuario_lista_alt[0]['usu_foto'] ?>">

                                    <img src="/images/usuario/<?php echo $view_usuario_lista_alt[0]['usu_foto'] ?>" class="img-fluid" alt="<?php echo $view_usuario_lista_alt[0]['usu_nome'] ?>">

                                  </a>

                                  <div class="mg-thumb-options" style="overflow: visible;">

                                    <div class="mg-zoom"><i class="fa fa-search"></i></div>

                                    <div class="mg-toolbar">

                                      <div class="mg-group float-right">                                        

                                        <button class="dropdown-toggle mg-toggle" data-toggle="dropdown" aria-expanded="true"><span class="caret"></span></button>

                                        <div class="dropdown-menu mg-dropdown" role="menu" x-placement="bottom-start" style="position: relative; transform: translate3d(271px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">

                                          <a class="dropdown-item text-1" href="/images/usuario/<?php echo $view_usuario_lista_alt[0]['usu_foto'] ?>" download="Imagem_usuario"><i class="fa fa-download"></i> <?php echo translate("Download"); ?></a>

                                          <a class="dropdown-item text-1" id="img_Del" href="#"><i class="fa fa-trash-o"></i> <?php echo translate("Apagar"); ?></a>

                                        </div>

                                      </div>

                                    </div>

                                  </div>

                                </div>

                                <!-- <div class="mg-description">

                                  <small class="float-left text-muted">Design, Websites</small>

                                  <small class="float-right text-muted">07/10/2017</small>

                                </div> -->

                              </div>

                            </div>

                          </div>



                          <?php endif; ?>



                        </div> 



                    </div>       



                    </div>

                  </section>

                </div>

            </div>  

            

            <div id="ref" class='clearfix'></div>  

            <span id="retorno" class="col-md-10"></span>            

            <a name="bt_usu_alterar" id="bt_usu_alterar"  href="javascript:$('#usu_img').uploadifive('upload')" class="btn btn-primary col-md-2 pull-right"><?php echo translate("Gravar"); ?></a>

               

        </div>

    </div>

</section>