<router base="nivel/alterar">

<input type="hidden" id="niv_idioma" value="<?php echo $view_nivel_info[0]['niv_idioma'];?>">

<input type="hidden" id="niv_id" value="<?php echo $view_nivel_info[0]['niv_id'];?>">                   

<header class="page-header">

    <h2><?php echo translate("Nível"); ?></h2>



    <div class="right-wrapper text-right">

        <?php $LANGUAGE_DEFAULT = unserialize(LANGUAGE_DEFAULT); ?>

        <?php $LANGUAGE_LIST = unserialize(LANGUAGE_LIST); ?>

        <?php if(!empty($LANGUAGE_LIST)): ?>        

          <?php foreach ($LANGUAGE_LIST as $lang): 

          $icon_lang = ($lang["D008_Icon"] == "en" ? "gb" : $lang["D008_Icon"]);

          ?>

          <a href="/backend/nivel/alterar/lang/<?php echo $lang['D008_Sigla']; ?>/id/<?php echo $view_usuario_lista_alt[0]['niv_id']; ?>" class="mb-1 mt-3 mr-0 ml-0 p-1 btn btn-xs btn-default"><i class="flag-icon flag-icon-<?php echo $icon_lang; ?>" style="font-size: 14px;"></i></a>         

        <?php endforeach; ?>   

        <?php endif; ?>

        <a name="nivAlt" id="nivAlt" href="#" class="mb-1 mt-3 mr-1 btn btn-xs btn-primary"><strong><?php echo translate("Gravar"); ?></strong></a>

        <a href="/backend/nivel/listar/lang/<?php echo $LANGUAGE_DEFAULT[0]; ?>" class="mb-1 mt-3 mr-1 ml-1 btn btn-xs btn-default"><strong><?php echo translate("Voltar"); ?></strong></a>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>

    </div>

</header>



<!-- start: file -->



<?php //$icon = ($view_usuario_lista_alt[0]['niv_idioma'] == "en" ? "gb" : $view_usuario_lista_alt[0]['niv_idioma']); ?>



<section class="card">

    <div class="card-body">

        <div class="invoice">

            <header class="clearfix">

                <div class="row">

                    <div class="col-sm-6 mt-3">

                        <h2 class="h2 mt-0 mb-4 text-dark font-weight-bold"><?php echo translate("Alterar Nível"); ?></h2>

                        <!-- <h4 class="h4 m-0 text-dark font-weight-bold">#76598345</h4> -->

                    </div>

                    <div class="col-sm-6 mt-3">

                        <div class="m-0 mb-4 pull-right">

                          <i class="flag-icon flag-icon-<?php echo $icon; ?>" style="font-size: 24px;"></i>

                        </div>

                    </div>

                </div>

            </header>



            <div class="row">

              <div class="col-md-4">

                <section class="card mb-4">

                  <header class="card-header">

                    <h2 class="card-title"><?php echo translate("Principal"); ?></h2>

                  </header>

                  <div class="card-body">

                    <form class="form-horizontal form-bordered" method="post">



                      <div class="form-group row">

                        <label class="col-lg-3 control-label text-lg-right pt-2" for="niv_nome"><?php echo translate("Nome"); ?></label>

                        <div class="col-lg-9">

                          <input type="text" id="niv_nome" class="form-control" value="<?php echo $view_nivel_info[0]['niv_nome'] ?>">

                        </div>

                      </div>

                         

                    </form>

                  </div>



                </section>



              </div>



              <div class="col-md-8">

                <section class="card mb-4">

                  <header class="card-header">

                    <h2 class="card-title">

                      <?php echo translate("Permissões"); ?>

                      

                      <div class="pull-right select-all-btn">

                        <?php echo translate("Selecionar todos"); ?>

                        <div class="switch switch-sm switch-primary">

                          <input id="toggle_all_permissions" type="checkbox" name="switch" data-plugin-ios-switch style="display:none;" />

                        </div>

                      </div>



                    </h2>

                  </header>

                  <div class="card-body">

                    

                    <!-- permissions start -->

                    <div class="permissions row">

                      <?php 

                        if (!empty($view_nivel_permissao)): 

                          $arr_nome = "";

                          $arr_permissao = array_shift($view_nivel_permissao);

                          array_shift($arr_permissao);



                          //gambiarra 1.0

                          $module_nice_names = array(

                            "per_menu" => translate("Menu"),
                            "per_conteudo" => translate("Conteúdo"),
                            "per_parceiros" => translate("Parceiros"),
                            "per_noticias" => translate("Notícias"),
                            "per_slide" => translate("Slide"),
                            "per_contatos" => translate("Contatos"),
                            "per_faq" => translate("FAQ"),
                            "per_configuracao" => translate("Configuração"),
                            "per_institucional" => translate("Institucional"),
                            "per_icones" => translate("Ícones"),
                            "per_produtos" => translate("Produtos"),
                            "per_portfolios" => translate("Portfolios"),
                            "per_testemunho" => translate("Testemunho"),
                            "per_servicos" => translate("Servicos"),
                            "per_calendario" => translate("Calendário"),
                            "per_eventos" => translate("Eventos"),
                            "per_equipe" => translate("Equipa"),
                            "per_cursos" => translate("Cursos"),
                            "per_unidades" => translate("Unidades"),
                            "per_landpage" => translate("Landpage"),
                            "per_banner" => translate("Banner"),
                            "per_processo" => translate("Processo"),
                            "per_recurso" => translate("Recurso"),
                            "per_pacote" => translate("Pacotes"),
                            "per_pedido" => translate("Pedido"),
                            "per_cliente" => translate("Clientes"),
                            "per_orcamento" => translate("Orçamentos"),
                            "per_vendedor" => translate("Vendedores"),
                            "per_area" => translate("Área"),
                            "per_distrito" => translate("Distrito"),
                            "per_cargo" => translate("Cargo"),
                            "per_especialidade" => translate("Especialidade"),
                            "per_tipo" => translate("Tipo"),
                            "per_treinamento" => translate("Treinamento")

                          );



                          $module_groups = array(

                            "btl" => array("nice_name" => translate("Plataforma"), "items" => array("per_treinamento", "per_vendedor", "per_cargo", "per_especialidade", "per_tipo", "per_produtos")),

                            "outros" => array("nice_name" => translate("Outros"), //os que não se inserem noutras áreas

                              "items" => array(

                                "per_menu",

                                "per_contatos",

                                "per_calendario",

                                "per_cursos",

                                "per_cliente"

                              )

                            ),

                            "sistema" => array("nice_name" => translate("Administração"), "items" => array("per_configuracao", "per_institucional")),

                          );

                        ?>



                        <?php foreach($module_groups as $module_group): ?>

                        <div class="permissions-group">

                          <header class="card-header">

                            <h2 class="card-title">

                            <?php echo $module_group["nice_name"] ?>                              

                              <!--div class="pull-right select-all-btn">

                                Selecionar todos

                                <div class="switch switch-sm switch-primary">

                                  <div class="ios-switch"><div class="on-background background-fill"></div><div class="state-background background-fill"></div><div class="handle"></div></div><input id="toggle_all_permissions" type="checkbox" name="switch" data-plugin-ios-switch="" style="display:none;">

                                </div>

                              </div-->

                            </h2>

                          </header>

                            

                          <div class="card-body">

                            <div class="permissions row">

                              

                              <!-- buttons -->

                              <?php foreach ($arr_permissao as $per_key => $permissao):

                                $nome = str_replace("per_", "", $per_key);

                                $nice_nome = !empty($module_nice_names[$per_key]) ? $module_nice_names[$per_key] : $nome;

                              ?>



                              <?php if(!in_array($per_key, $module_group["items"])) continue; ?>

                                                  

                              <div class="col-md-3">

                                  <label class="col-md-8 col-sm-8 col-xs-8"><?php echo $nice_nome; ?></label>           

                                  <div class="col-md-4 col-sm-4 col-xs-4 switcher-container">

      

                                    <div class="switch switch-sm switch-primary">

                                      <input id="nivel_permissao_<?php echo $nome; ?>" type="checkbox" name="switch" data-plugin-ios-switch <?php echo ($permissao == 1) ? "checked" : ""; ?> style="display:none;" />

                                    </div>



                                  </div>

                                  <p class="clearfix"></p>

                              </div>

                              <?php $arr_nome .= $nome.",";  ?>

                              <?php endforeach; ?>



                            </div>

                          </div>



                        

                      

                        <?php endforeach; ?>
                        

                        <?php endif; 

                          $arr_nome = substr($arr_nome,0,-1);

                          $arr_col = explode(",", $arr_nome);

                        ?>

                        

                        <input type="hidden" id="nivel_permissao_array" value='<?php echo json_encode($arr_col); ?>'>

                      </div>

                      <!-- permissions end -->



                  </div>



                </section>



                



              </div>



            </div>  

            

            <div id="ref" class='clearfix'></div>  

            <span id="retorno" class="col-md-10"></span>            

            <a name="nivAlt" id="nivAlt"  href="javascript:$('#niv_img').uploadifive('upload')" class="btn btn-primary col-md-2 pull-right"><?php echo translate("Gravar"); ?></a>

               

        </div>

    </div>

</section>