<router base="produto/registar">
<?php $LANGUAGE_DEFAULT = unserialize(LANGUAGE_DEFAULT); ?>
<input type="hidden" id="idioma" class="icon" value="<?php echo $LANGUAGE_DEFAULT[0]; ?>" />
<?php $config = unserialize (CONFIG_DB); ?>
<input type="hidden" id="dominio" value="<?php echo $config[0]['D001_Site'];?>">
<header class="page-header">
    <h2>Produto</h2>
    <div class="right-wrapper text-right">
        <?php $LANGUAGE_DEFAULT = unserialize(LANGUAGE_DEFAULT); ?>
        <?php $LANGUAGE_LIST = unserialize(LANGUAGE_LIST); ?>
        <a name="bt_produto_cadastrar" id="bt_produto_cadastrar"  href="javascript:$('#img').uploadifive('upload')" class="mb-1 mt-3 ml-2 mr-1 btn btn-xs btn-primary"><strong>Gravar</strong></a>
        <a href="/backend/produto/listar/lang/<?php echo $LANGUAGE_DEFAULT[0]; ?>" class="mb-1 mt-3 mr-1 ml-1 btn btn-xs btn-default"><strong>Voltar</strong></a>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>
    </div>
</header>
<?php $icon = ($LANGUAGE_DEFAULT[0] == "en" ? "gb" : $LANGUAGE_DEFAULT[0]); ?>
<!-- start: deste -->
<section class="card">
    <div class="card-body">
        <div class="invoice">
            <header class="clearfix">
                <div class="row">
                    <div class="col-sm-6 mt-3">
                        <h2 class="h2 mt-0 mb-4 text-dark font-weight-bold">Criar Conteúdo</h2>
                    </div>
                    <div class="col-sm-6 mt-3">
                        <!-- <div class="m-0 mb-4 pull-right">
                          <i class="flag-icon flag-icon-<?php //echo $icon; ?>" style="font-size: 24px;"></i>
                        </div> -->
                    </div>
                </div>
            </header>
            <div class="row">
              <div class="col-md-8">
                <section class="card mb-4">
                  <header class="card-header">
                    <h2 class="card-title pull-left">Principal</h2>
                  </header>
                  <div class="card-body">
                    <form class="form-horizontal form-bordered" method="post">
                      <div class="form-group row">
                        <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Título</label>
                        <div class="col-lg-9">
                          <input type="text" id="titulo" class="form-control">
                        </div>
                      </div>                     
                      <div class="form-group row">
                        <label class="col-lg-3 control-label text-lg-right pt-2" for="textareaDefault">Breve descrição</label>
                        <div class="col-lg-9">
                          <textarea class="form-control" id="chamada" rows="5"></textarea>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Descrição detalhada</label>
                        <div class="col-lg-9">
                          <!-- <textarea class="form-control" name="produto_texto" id="produto_texto"></textarea> -->
                          <?php
                            require_once $_SERVER['DOCUMENT_ROOT']."/backend/public/vendor/ckeditor/ckeditor.php";
                            require_once $_SERVER['DOCUMENT_ROOT']."/backend/public/vendor/ckfinder/ckfinder.php";

                            $initialValue = "";
                            $CKEditor = new CKEditor();
                            $CKEditor->basePath = '/backend/public/vendor/ckeditor/';
                            CKFinder::SetupCKEditor($CKEditor, '/backend/public/vendor/ckfinder/');
                            $CKEditor->editor("texto", $initialValue);
                          ?>
                        </div>
                      </div>

                      <div class="form-group row">
                        <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Ordem</label>
                        <div class="col-lg-9">
                          <input type="text" id="ordem" class="form-control">
                        </div>
                      </div>

                      <div class="form-group row">
                        <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Preço</label>
                        <div class="col-lg-9">
                          <input type="text" id="preco" class="form-control">
                        </div>
                      </div>
                     
                    </form>
                  </div>
                </section>
              </div>
              <div class="col-md-4">

                <section class="card mb-4">
                    <header class="card-header">
                      <h2 class="card-title">Informações</h2>
                    </header>
                    <div class="card-body">


                      <div class="form-group row">

                        <label class="col-sm-3 control-label text-sm-right pt-2">Status</label>
                        <div class="btn-group col-sm-9 pull-right" data-toggle="buttons">

                          <label class="btn btn-primary active">
                            <input type="radio" name="destaque" id="option1" autocomplete="off" value="true" checked> Ativo
                          </label>
                          <label class="btn btn-primary">
                            <input type="radio" name="destaque" id="option2" autocomplete="off"  value="false"> Inativo
                          </label>
                        </div>
                      </div>

                      <div class="form-group row">

                        <label class="col-sm-3 control-label text-sm-right pt-2">Imagem</label>
                        <div class="col-sm-9 media-gallery">
                          <div id="queue" class="mt-3 mb-3"></div>
                          <input id="img" name="img" type="file" multiple>
                          <input type="hidden" id="timestamp" value="<?php echo $timestamp = time();?>">
                          <input type="hidden" id="unique_salt" value="<?php echo md5('unique_salt' . $timestamp);?>">
                          <!-- <span class="pull-right">tam: 1920px x 480px</span> -->
                        </div>
                      </div>

                      <div class="form-group row">
                        <h5 class="control-label text-sm-right pt-2">Tipo de Página</h5>
                        <select id="controller" class="form-control" required disabled>
                        <option value="0"></option>
                        <?php
                        if(isset($view_modulo)):
                            foreach ($view_modulo as $modulo):
                                if($modulo["mod_modulo"] == "produto"):
                                   echo  '<option value="'.$modulo["mod_modulo"].'" selected>'.$modulo["mod_titulo"].'</option>';
                                else:
                                   echo  '<option value="'.$modulo["mod_modulo"].'" >'.$modulo["mod_titulo"].'</option>';
                                endif;
                            endforeach;
                        endif; ?>
                        </select>
                      </div>

                     <!--  <div class="form-group row">
                        <h4 class="control-label text-sm-right pt-2">Categoria</h4>
                        <select id="categoria" class="form-control" required>
                          <option value="0">Selecione</option>
                          <?php
                          /* if(isset($view_categoria)):
                              foreach ($view_categoria as $categoria):
                                  echo  '<option value="'.$categoria["D007_Uid"].'" >'.$categoria["D007_Titulo"].'</option>';
                              endforeach;
                          endif;  */
                          ?>
                        </select>
                      </div>

                      <div class="form-group row">
                        <h4 class="control-label text-sm-right pt-2">Sub-Categoria - Lv1</h4>
                        <select id="subcategoria" class="form-control">
                          <option value="0">Selecione uma categoria</option>
                        </select>
                      </div>

                      <div class="form-group row">
                        <h4 class="control-label text-sm-right pt-2">Sub-Categoria - Lv2</h4>
                        <select id="ssubcategoria" class="form-control">
                          <option value="0">Selecione uma sub-categoria Lv1</option>
                        </select>
                      </div> -->

                    </div>
                  </section>
                </div>
            </div>

            <div id="ref" class='clearfix'></div>
            <span id="retorno" class="col-md-10"></span>
            <a name="bt_produto_cadastrar" id="bt_produto_cadastrar"  href="javascript:$('#img').uploadifive('upload')" class="btn btn-primary col-md-2 pull-right">Gravar</a>

        </div>
    </div>
</section>
<!-- end: deste -->
