<router base="pagina/listar">
<?php 
    $languageLIST = unserialize (LANGUAGE_LIST);
    $languageDEFAULT = unserialize (LANGUAGE_DEFAULT);
?>
<header class="page-header">
    <h2>Páginas</h2>
    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Home</span></li>
            <li><span>Páginas</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>
    </div>
</header>

<!-- start: page -->
<section class="card">
    <div class="card-body">
        <div class="invoice">
            <header class="clearfix">
                <div class="row">
                    <div class="col-sm-6 mt-3">
                        <h2 class="h2 mt-0 mb-4 text-dark font-weight-bold">Páginas Registadas</h2>
                        <!-- <h4 class="h4 m-0 text-dark font-weight-bold">#76598345</h4> -->
                    </div>
                    <div class="col-sm-6 mt-3">
                        <div class="m-0 mb-4 pull-right">
                            <a href="/backend/pagina/registar" id="pagCad" class="mb-1 mt-1 mr-1 btn btn-primary"> <strong>Criar Página</strong></a>
                        </div>
                    </div>
                </div>
            </header>

            <table class="table table-bordered table-striped mb-0" id="datatable-tabletools">
                <thead>                    
                    <tr>
                        <th style="width: 5%">ID</th>
                        <th style="width: 40%">TÍTULO</th>
                        <th style="width: 20%">TRADUÇÃO</th>
                        <th style="width: 15%">TIPO</th>
                        <th style="width: 10%">STATUS</th>
                        <th style="width: 10%">AÇÕES</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                    if(!empty($view_pagina_lista)):
                    foreach ($view_pagina_lista as $pagina): ?>
                    <tr id="<?php echo $pagina['D007_Uid'] ?>">
                        <td class="v-align-middle"><?php echo $pagina['D007_Uid']; ?></td>
                        <td class="v-align-middle"><a href="/backend/pagina/alterar/lang/<?php echo $languageDEFAULT[0];?>/ref/<?php echo $pagina["D007_Referencia"]?>"><strong><?php echo $pagina['D007_Titulo']; ?></strong></a></td>
                        <td class="v-align-middle">
                        <ul class="language">
                        <?php 
                            foreach ($languageLIST as $idioma): 
                                if($languageDEFAULT[0] != $idioma["D008_Sigla"]):
                        ?>  
                        <li>                                        
                            <a href="/backend/pagina/alterar/lang/<?php echo $idioma["D008_Sigla"]?>/ref/<?php echo $pagina["D007_Referencia"]?>" class="menu-item"><i class="flag-icon flag-icon-<?php echo $idioma["D008_Icon"]?>"></i></a>
                        </li>
                        <?php
                                endif; 
                            endforeach; 
                        ?>
                        </ul>                        
                        </td> 
                        <td>
                            <?php
                        $controller = array("institucional" => "Quem Somos","noticias" => "Blog","servicos" => "Serviços","index" => "Homepage","portfolios" => "Portfolio","contato" => "Contacto");
                        if(isset($controller)):
                            foreach ($controller as $ctrl => $tipo): 
                              if($pagina['D007_Controle'] == $ctrl ){
                                echo  $tipo;
                              }
                            endforeach;
                        endif; ?>
                        </td>                       
                        <td class="v-align-middle">
                        <?php
                        echo $pagina['D007_Destaque'];
                        ?>
                        </td>
                        <td class="actions">
                            <a class="pagDel" href="#modalAnim" ref-id="<?php echo $pagina['D007_Uid'] ?>">
                                <i class="fa fa-trash-o fa-lg"></i>
                            </a>
                            <input type="hidden" class="icon" value="<?php echo $pagina['D007_Uid'] ?>" />
                        </td>
                    </tr>
                    <?php endforeach;
                    endif; ?>
                </tbody>
            </table>
               
        </div>
    </div>
</section>

<!-- end: page -->