<div class="col-md-12">

  <div class=" titleIdent"> 

      <h2  class="col-md-10">Cadastrar Submenu</h2><span class="closed_acao col-md-2"><i class="pg-close_line pull-right"></i></span>

    <br>

  </div>

  <div class="panel panel-default"> 

    <div class="panel-header">

    <br>

    </div>

    <div class="panel-body">

      <div class="form-group form-group-default required">

        <label>Nome</label>

        <input type="text" id="smenu_nome" class="form-control" required>

      </div>

      <div class="form-group form-group-default">

        <label>Link</label>

        <input type="text" id="smenu_link" class="form-control">

      </div>

      

      <div class="row">

        <div class="col-sm-6">

          <div class="form-group form-group-default">

            <label>Ordem</label>

            <input type="text" id="smenu_ordem" class="form-control">

          </div>

        </div>

        <div class="col-sm-6">

          <div class="form-group form-group-default styleradio">

            <div class="input-group">

              <div class="btn-group" data-toggle="buttons">

                <label class="col-sm-3 pull-left">Status</label>

                <div class="btn-group col-sm-9 pull-right" data-toggle="buttons">

                  <label class="btn btn-primary active">

                    <input type="radio" name="smenu_tipo" id="option1" autocomplete="off" value="_self" checked> ATIVO

                  </label>

                  <label class="btn btn-primary">

                    <input type="radio" name="smenu_tipo" id="option2" autocomplete="off"  value="_blank"> INATIVO

                  </label>

                </div>

              </div>

             </div>

          </div>

        </div>

      </div>

    </div>

  </div>

  <div class=" titleIdent"> 

      <span id="retorno" class="col-md-10"></span><a name="bt_smenu_cadastrar" id="bt_smenu_cadastrar"  href="javascript:$$" class="btn btn-primary col-md-2">Cadastrar</a>

    <br>

  </div>

</div>

<div id="ref" class='clearfix'></div>