
<div class="container-fluid container-fixed-lg">
  <br>
  <div class="row icon-set-preview">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title">Pages icon
          </div>
        </div>
        <div class="panel-body">
           <div class="fa-item col-md-3 col-sm-4"><i class="pg-signals"></i> pg-signals</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-crop"></i> pg-crop</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-folder_alt"></i> pg-folder_alt</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-folder"></i> pg-folder</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-theme"></i> pg-theme</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-battery_empty"></i> pg-battery_empty</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-battery"></i> pg-battery</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-note"></i> pg-note</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-server_hard"></i> pg-server_hard</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-servers"></i> pg-servers</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-menu_justify"></i> pg-menu_justify</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-credit_card"></i> pg-credit_card</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-fullscreen_restore"></i> pg-fullscreen_restore</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-fullscreen"></i> pg-fullscreen</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-minus"></i> pg-minus</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-minus_circle"></i> pg-minus_circle</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-plus_circle"></i> pg-plus_circle</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-refresh_new"></i> pg-refresh_new</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-close_line"></i> pg-close_line</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-close"></i> pg-close</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_down"></i> pg-arrow_down</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_left_line_alt"></i> pg-arrow_left_line_alt</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_left"></i> pg-arrow_left</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_lright_line_alt"></i> pg-arrow_lright_line_alt</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_maximize_line"></i> pg-arrow_maximize_line</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_maximize"></i> pg-arrow_maximize</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_minimize_line"></i> pg-arrow_minimize_line</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_minimize"></i> pg-arrow_minimize</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_right"></i> pg-arrow_right</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-arrow_up"></i> pg-arrow_up</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-more"></i> pg-more</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-bag"></i> pg-bag</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-bag1"></i> pg-bag1</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-bold"></i> pg-bold</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-calender"></i> pg-calender</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-camera"></i> pg-camera</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-centeralign"></i> pg-centeralign</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-charts"></i> pg-charts</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-clock"></i> pg-clock</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-comment"></i> pg-comment</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-contact_book"></i> pg-contact_book</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-credit_card_line"></i> pg-credit_card_line</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-cupboard"></i> pg-cupboard</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-desktop"></i> pg-desktop</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-download"></i> pg-download</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-eraser"></i> pg-eraser</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-extra"></i> pg-extra</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-form"></i> pg-form</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-grid"></i> pg-grid</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-home"></i> pg-home</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-image"></i> pg-image</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-inbox"></i> pg-inbox</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-indent"></i> pg-indent</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-italic"></i> pg-italic</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-laptop"></i> pg-laptop</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-layouts"></i> pg-layouts</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-layouts2"></i> pg-layouts2</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-layouts3"></i> pg-layouts3</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-layouts4"></i> pg-layouts4</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-leftalign"></i> pg-leftalign</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-like"></i> pg-like</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-like1"></i> pg-like1</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-lock"></i> pg-lock</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-mail"></i> pg-mail</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-map"></i> pg-map</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-menu_lv"></i> pg-menu_lv</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-menu"></i> pg-menu</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-movie"></i> pg-movie</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-ordered_list"></i> pg-ordered_list</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-outdent"></i> pg-outdent</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-phone"></i> pg-phone</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-plus"></i> pg-plus</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-power"></i> pg-power</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-printer"></i> pg-printer</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-refresh"></i> pg-refresh</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-resize"></i> pg-resize</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-right_align"></i> pg-right_align</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-save"></i> pg-save</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-search"></i> pg-search</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-sent"></i> pg-sent</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-settings_small_1"></i> pg-settings_small_1</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-settings_small"></i> pg-settings_small</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-settings"></i> pg-settings</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-shopping_cart"></i> pg-shopping_cart</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-social"></i> pg-social</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-spam"></i> pg-spam</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-suitcase"></i> pg-suitcase</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-tables"></i> pg-tables</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-tablet"></i> pg-tablet</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-telephone"></i> pg-telephone</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-text_style"></i> pg-text_style</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-trash_line"></i> pg-trash_line</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-trash"></i> pg-trash</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-ui"></i> pg-ui</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-underline"></i> pg-underline</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-unordered_list"></i> pg-unordered_list</div>
              <div class="fa-item col-md-3 col-sm-4"><i class="pg-video"></i> pg-video</div>
        </div>
      </div>
    </div>
  </div>
   
</div>