<?php require_once("pagina.segura.php"); ?>

<router base="cargo/listar">
<?php $LANGUAGE_DEFAULT = unserialize(LANGUAGE_DEFAULT); ?>
<input type="hidden" id="idioma" class="icon" value="<?php echo $LANGUAGE_DEFAULT[0]; ?>" />
<header class="page-header">
    <h2><?php echo translate("Cargos"); ?></h2>

    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/backend/index/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span><?php echo translate("Home"); ?></span></li>
            <li><span><?php echo translate("Cargos"); ?></span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>
    </div>
</header>

<!-- start: page -->

<section class="card">
    <div class="card-body">
        <div class="invoice">
            <header class="clearfix">
                <div class="row">
                    <div class="col-sm-6 mt-3">
                        <h2 class="h2 mt-0 mb-4 text-dark font-weight-bold"><?php echo translate("Cargos"); ?></h2>
                        <!-- <h4 class="h4 m-0 text-dark font-weight-bold">#76598345</h4> -->
                    </div>
                    <div class="col-sm-6 mt-3">
                        <div class="m-0 mb-4 pull-right">
                            <a href="/backend/cargo/registar/lang/<?php echo $LANGUAGE_DEFAULT[0]; ?>" id="cliCad" class="mb-1 mt-1 mr-1 btn btn-primary"> <strong><?php echo translate("Registar Área"); ?></strong></a>
                        </div>
                    </div>
                </div>
            </header>

            <table class="table table-bordered table-striped mb-0" id="datatable-tabletools">
                <thead>
                    <tr>
                        <th width='8%'><?php echo translate("ID"); ?></th>
                        <th width='62%'><?php echo translate("NOME"); ?></th>
                        <th width='15%'><?php echo translate("STATUS"); ?></th>
                        <th width='15%'><?php echo translate("AÇÕES"); ?></th>
                    </tr>
                </thead>
                <tbody>
                  <?php
                  if(!empty($view_cargo_lista)):
                  foreach ($view_cargo_lista as $cargo):
                  ?>
                  <tr id="<?php echo $cargo['cargo_id'] ?>">
                      <td><?php echo $cargo['cargo_id']; ?></td>
                      <td><a class="text-default" href="/backend/cargo/alterar/ref/<?php echo $cargo['cargo_id'];?>" title="Alterar"><?php echo $cargo['cargo_nome']; ?></a></td>
                      <td>
                      <?php 
                        if($cargo['cargo_status'] == "sim"): 
                            echo translate("Ativo");
                        else: 
                            echo translate("Inativo");
                        endif; 
                        ?>  
                      </td>
                      <td class="actions">
                        <?php //if( $_SESSION['nivel_acesso'] == 1 ): ?>
                        <input type="hidden" class="icon" value="<?php echo $cargo['cargo_id']?>" />
                        <a  class="cargoDel" ref-id="<?php echo $cargo['cargo_id']?>" ref-name="<?php echo $cargo['cargo_nome'];?>" href="#modalAnim">
                            <i class="fa fa-trash-o fa-lg text-danger"></i>
                        </a>
                        <?php //endif; ?>
                      </td>
                  </tr>
                  <?php endforeach;
                  endif; ?>
                </tbody>
            </table>

        </div>
    </div>
</section>

<!-- end: page -->