<?php require_once("pagina.segura.php"); ?>

<router base="lead/list">

<header class="page-header">
    <h2>Lead Conversion</h2>

    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/backend/index/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Home</span></li>
            <li><span>Lead Conversion</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-calendar"></i></a>
    </div>
</header>

<div class="row p-0 m-0">			
            <div class="col-xs-12 col-md-6 col-lg-3 col-xl-3 p-1">
                <section class="card mb-2">
                    <a href="/backend/lead/list/ref/noclassification" class="lead_a">
                        <div class="card-body bg-red">
                            <div class="widget-summary lead-conversion-red">
                                <h4 class="title">S/Classificação</h4>
                                <div class="info">
                                    <strong><?php echo $view_funil_visitantes; ?></strong>
                                </div>									
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3 col-xl-3 p-1">						
                <section class="card mb-2">
                    <a href="/backend/lead/list/ref/leads" class="lead_a">
                        <div class="card-body bg-yellow">
                            <div class="widget-summary lead-conversion-yellow">
                                <h4 class="title">Leads</h4>
                                <div class="info">
                                    <strong><?php echo $view_funil_leads; ?></strong>
                                </div>									
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3 col-xl-3 p-1">						
                <section class="card mb-2">
                    <a href="/backend/lead/list/ref/prospects" class="lead_a">
                        <div class="card-body bg-orange">
                            <div class="widget-summary lead-conversion-orange">
                                <h4 class="title">Prospects</h4>
                                <div class="info">
                                    <strong><?php echo $view_funil_conversao; ?></strong>
                                </div>									
                            </div>
                        </div>
                    </a>
                </section>
            </div>
            <div class="col-xs-12 col-md-6 col-lg-3 col-xl-3 p-1">
                <section class="card mb-2">
                    <a href="/backend/lead/list/ref/clients" class="lead_a">
                        <div class="card-body bg-green">
                            <div class="widget-summary lead-conversion-green">
                                <h4 class="title">Clients</h4>
                                <div class="info">
                                    <strong><?php echo $view_funil_clientes; ?></strong>
                                </div>									
                            </div>
                        </div>
                    </a>
                </section>
            </div>
        </div>

<section class="card">
    <div class="card-body">
        <div class="invoice">
            <header class="clearfix">
                <div class="row">
                    <div class="col-7 mt-3">
                        <h2 class="h2 mt-0 mb-4 text-dark font-weight-bold"><?php echo $view_lead_title; ?></h2>
                    </div>
                    <div class="col-5 mt-3">
                        <?php if($view_ref != "noclassification" ): ?>                        
                        <div class="form-group row m-0 mb-4 pull-right">                                               
                            <select name="btn_leads" class="form-control mb-3">                                                                 
                                <option value="0">-</option>                                
                                <?php $arr_leads = array(1 => "Leads", 2 => "Prospects", 3 => "Clients"); ?>
                                <?php foreach($arr_leads as $action_id => $action ): 
                                    if ($view_ref_id == $action_id ):
                                        $selected = "selected";                                    
                                ?>
                                <option value="<?php echo $action_id ?>" <?php echo $selected; ?> ><?php echo $action; ?></option>  
                                    <?php else: ?>
                                <option value="<?php echo $action_id ?>"><?php echo $action; ?></option>  
                                <?php endif; ?>
                                <?php endforeach; ?>                                                                
                            </select>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </header>
            
            <table class="table table-bordered table-striped mb-0 leadTable" name="leadTable" id="datatable-tabletools">
                <thead>
                    <tr>                        
                        <th width='8%'>  
                            <div class="checkbox-lead checkbox-default">
                                <input type="checkbox" name="check_lead"> 
                                <label></label>                         
                            </div>                            
                        </th>
                        <?php if($view_ref == "noclassification" ): ?>                            
                        <th width='60%'>CLIENTE</th>
                        <?php else: ?>
                        <th width='30%'>NOME</th>
                        <th width='30%'>CLIENTE</th>
                        <?php endif; ?>
                        <th width='20%'>EMAIL</th>
                        <th width='12%'>TELEFONE</th>
                    </tr>
                </thead>
                <tbody>                   
                    <?php
                    if(!empty($view_data)):
                        $num = 1;  
                        foreach ($view_data as $data):
                    ?>
                    <tr id="<?php echo $data['cont_id'] ?>">                        
                        <td><?php echo $num; ?></td>                        
                        <?php if($view_ref == "noclassification" ): ?>                            
                        <td>
                            <?php if($view_ref == "noclassification"): ?>
                            <a href="/backend/cliente/perfil/ref/<?php echo $data["ref"]; ?>"><?php echo $data["cont_nome"]; ?></a>
                            <?php else: ?>                            
                            <?php echo $data["cont_nome"]; ?>
                            <?php endif; ?>
                        </td>
                        <?php else: ?>
                        <td>
                            <?php if($view_ref == "noclassification"): ?>
                            <a href="/backend/cliente/perfil/ref/<?php echo $data["ref"]; ?>"><?php echo $data["cont_nome"]; ?></a>
                            <?php else: ?>                            
                            <?php echo $data["cont_nome"]; ?>
                            <?php endif; ?>
                        </td>
                        <td><?php echo $data['cli_id']; ?></td>                        
                        <?php endif; ?>
                        <td><?php echo $data['cont_email']; ?></td>
                        <td><?php echo $data['cont_telemovel']; ?></td>
                  </tr>
                  <?php $num++; endforeach;
                  endif; ?>
                </tbody>
            </table>

        </div>
    </div>
</section>

<!-- end: page -->