<router base="cliente/listar">
<?php $LANGUAGE_DEFAULT = unserialize(LANGUAGE_DEFAULT); ?>
<input type="hidden" id="idioma" class="icon" value="<?php echo $LANGUAGE_DEFAULT[0]; ?>" />
<?php date_default_timezone_set('Europe/Lisbon'); ?>
<?php setlocale(LC_ALL, 'pt_PT'); ?>
<header class="page-header">
    <h2><?php echo translate("Logs - Pesquisas exportadas"); ?></h2>

    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/backend/index/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span><?php echo translate("Logs"); ?></span></li>
            <li><span><?php echo translate("Pesquisas exportadas"); ?></span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<!-- start: page -->
<div class="timeline timeline-simple changelog">
    <div class="tm-body">
        <ol class="tm-items">
            <?php if(!empty($view_logs)): ?>            
            <?php foreach ($view_logs as $log): ?>
            <li>
                <div class="tm-box">  
                    <?php $action = ($log["action"] == "excel" ? "success" : "danger"); ?>
                    <h4 class="release-date"><?php echo strftime("%d %B - %H:%M", strtotime($log["date"])); ?> </h4> <span class="badge badge-<?php echo $action; ?>"><?php echo $log["action"]; ?></span>
                    <ul class="list-unstyled">                        
                        <li><?php echo translate("Utilizador"); ?>: <strong><?php echo $log["user"]; ?></strong></li>
                        <li><?php echo translate("Arquivo"); ?>: <strong><?php echo $log["action"]; ?></strong></li>
                        <li><?php echo translate("Filtro"); ?>: <strong><?php echo $log["filter"]; ?></strong></li>
                    </ul>
                </div>
            </li>
            <?php endforeach; ?>
            <?php endif; ?>     
        </ol>
    </div>
</div>
<!-- end: page -->