<?php 
$config = unserialize (CONFIG_DB);
$permissao = unserialize(PERMISSAO_DB);
$languageDEFAULT = unserialize(LANGUAGE_DEFAULT); 

function impar($var)
{
    return($var & 1);
}
$arr = array_filter($permissao, "impar");
$habilitados = array_keys($arr);

?>
<div class="sidebar-header">
  <div class="sidebar-title">
      <input type="text" name="nav_search" placeholder="<?php echo translate("Buscar"); ?>" class="search-nav" >
  </div>
  <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
      <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
  </div>
</div>
<div class="nano">
    <div class="nano-content">
        <nav id="menu" class="nav-main" role="navigation">
        
            <ul class="nav nav-main">
                <!--nav-expanded nav-active-->
                <li data-search="<?php echo translate("Dashboard"); ?>">
                  <a href="/../backend/index/" class="nav-link">
                    <i class="fa fa-home" aria-hidden="true"></i>
                    <span><?php echo translate("Dashboard"); ?></span>
                  </a>
                </li>
                <?php if(in_array('per_cliente', $habilitados)) { ?>        
                <li data-search="<?php echo translate("Calendário"); ?>">
                  <a href="/../backend/calendario">
                    <i class="fa fa-calendar" aria-hidden="true"></i>
                    <span><?php echo translate("Calendário"); ?></span>
                  </a>
                </li>
                <?php } ?>
                <?php if(in_array('per_cliente', $habilitados)) { ?>        
                <li class="nav-parent" data-search="<?php echo translate("Clientes"); ?>">
                  <a href="javascript:void(0);">
                    <i class="fa fa-user-plus" aria-hidden="true"></i>
                    <span><?php echo translate("Clientes"); ?></span>
                  </a>
                  <ul class="nav nav-children">
                    <li data-search="<?php echo translate("Ver todos"); ?>">
                      <a class="nav-link" href="/../backend/cliente/listar/lang/<?php echo $languageDEFAULT[0]; ?>"><?php echo translate("Ver todos"); ?></a>
                    </li>
                    <li data-search="<?php echo translate("Adicionar"); ?>">
                      <a class="nav-link" href="/../backend/cliente/registar/lang/<?php echo $languageDEFAULT[0]; ?>"><?php echo translate("Adicionar"); ?></a>
                    </li>
                  </ul>
                </li>
                <?php } ?>
                
                
                
                <?php if(in_array('per_produtos', $habilitados)) { ?>
                <li data-search="<?php echo translate("Produtos"); ?>">
                  <a class="nav-link" href="/../backend/produto/listar/lang/<?php echo $languageDEFAULT[0]; ?>">
                    <i class="fa fa-archive" aria-hidden="true"></i>
                    <span><?php echo translate("Produtos"); ?></span>
                  </a>
                </li> 
                <?php } ?>  

                <?php if($_SESSION['nivel_acesso'] == 1 || $_SESSION['nivel_acesso'] == 2 ):  ?>
                
                <li class="nav-parent" data-search="<?php echo translate("Registros"); ?>">
                  <a href="javascript:void(0);">
                    <i class="fa fa-th-list" aria-hidden="true"></i>
                    <span><?php echo translate("Registros"); ?></span>
                  </a>
                  <ul class="nav nav-children">
                    <li data-search="<?php echo translate("Área de negócios"); ?>">
                      <a class="nav-link" href="/../backend/area/listar"><?php echo translate("Área de negócios"); ?></a>
                    </li>
                    <li data-search="<?php echo translate("Cargos"); ?>">
                      <a class="nav-link" href="/../backend/cargo/listar"><?php echo translate("Cargos"); ?></a>
                    </li>
                    <li data-search="<?php echo translate("Especialidades"); ?>">
                      <a class="nav-link" href="/../backend/especialidade/listar"><?php echo translate("Especialidades"); ?></a>
                    </li>
                    <li data-search="<?php echo translate("Tipos"); ?>">
                      <a class="nav-link" href="/../backend/tipo/listar"><?php echo translate("Tipos"); ?></a>
                    </li>
                    <!-- <li>
                      <a class="nav-link" href="/../backend/vendedor/listar">Vendedor</a>
                    </li> -->
                  </ul>
                </li>   

                <?php endif; ?>               
             
                <?php if(in_array('per_configuracao', $habilitados)): ?>
                <li class="nav-parent" data-search="<?php echo translate("Utilizadores"); ?>">
                  <a class="nav-link" href="javascript:void(0);">
                    <i class="fa fa-group" aria-hidden="true"></i>
                    <span><?php echo translate("Utilizadores"); ?></span>
                  </a>
                  <ul class="nav nav-children">
                    <li data-search="<?php echo translate("Adicionar"); ?>">
                      <a href="/../backend/usuario/registar"><?php echo translate("Adicionar"); ?></a>
                    </li>
                    <li data-search="<?php echo translate("Listar utilizadores"); ?>">
                      <a href="/../backend/usuario/listar"><?php echo translate("Listar utilizadores"); ?></a>
                    </li>
                    <?php if($_SESSION['nivel_acesso'] == 1 || $_SESSION['nivel_acesso'] == 2 ):  ?>
                    <li data-search="<?php echo translate("Níveis e permissões"); ?>">
                      <a class="nav-link" href="/../backend/nivel/listar"><?php echo translate("Níveis e permissões"); ?></a>
                    </li>
                    <?php endif; ?>
                  </ul>
                </li>
                <?php endif; ?>
                
                <li class="nav-parent" data-search="<?php echo translate("Leads Conversion"); ?>">
                  <a class="nav-link" href="javascript:void(0);">
                    <i class="fa fa-filter" aria-hidden="true"></i>
                    <span><?php echo translate("Leads Conversion"); ?></span>
                  </a>
                  <ul class="nav nav-children">                                    
                    <li data-search="<?php echo translate("S/ Classificação"); ?>">
                      <a class="nav-link" href="/../backend/lead/list/ref/noclassification">
                      <i class="fa fa-circle circle_sclassification" aria-hidden="true" ></i>
                      <span><?php echo translate("S/ Classificação"); ?></span>
                      </a>
                    </li>
                    <li data-search="<?php echo translate("Leads"); ?>">
                      <a class="nav-link" href="/../backend/lead/list/ref/leads">
                      <i class="fa fa-circle circle_leads" aria-hidden="true"></i>
                      <span><?php echo translate("Leads"); ?></span>
                      </a>
                    </li>
                    <li data-search="<?php echo translate("Prospects"); ?>">
                      <a class="nav-link" href="/../backend/lead/list/ref/prospects">
                      <i class="fa fa-circle circle_prospects" aria-hidden="true"></i>
                      <span><?php echo translate("Prospects"); ?></span>
                      </a>
                    </li>
                    <li data-search="<?php echo translate("Clients"); ?>">
                      <a class="nav-link" href="/../backend/lead/list/ref/clients">
                      <i class="fa fa-circle circle_clients" aria-hidden="true"></i>
                      <span><?php echo translate("Clients"); ?></span>
                      </a>
                    </li>                    
                  </ul>
                </li>

                <?php if($_SESSION['nivel_acesso'] == 1 || $_SESSION['nivel_acesso'] == 2 ):  ?>
                  <?php if(in_array('per_configuracao', $habilitados)): ?>
                  <li class="nav-parent" data-search="<?php echo translate("Logs"); ?>">
                    <a class="nav-link" href="javascript:void(0);">
                      <i class="fa fa-clock-o" aria-hidden="true"></i>
                      <span><?php echo translate("Logs"); ?></span>
                    </a>
                    <ul class="nav nav-children">                                    
                      <li data-search="<?php echo translate("Pesquisas exportadas"); ?>">
                        <a class="nav-link" href="/../backend/log/dbgerados"><?php echo translate("Pesquisas exportadas"); ?></a>
                      </li>
                      <li data-search="<?php echo translate("Controlo de acesso"); ?>">
                        <a class="nav-link" href="/../backend/log/logins"><?php echo translate("Controlo de acesso"); ?></a>
                      </li>
                      <li data-search="<?php echo translate("Acompanhamento de clientes"); ?>">
                        <a class="nav-link" href="/../backend/log/eventos"><?php echo translate("Acompanhamento de clientes"); ?></a>
                      </li>
                    </ul>
                  </li>
                  <?php endif; ?>
                <?php endif; ?>

                <?php if(in_array('per_configuracao', $habilitados)): ?>
                <li class="nav-parent" data-search="<?php echo translate("Configuração"); ?>">
                  <a class="nav-link" href="javascript:void(0);">
                    <i class="fa fa-cogs" aria-hidden="true"></i>
                    <span><?php echo translate("Configuração"); ?></span>
                  </a>
                  <ul class="nav nav-children">
                    <li data-search="<?php echo translate("Empresa"); ?>">
                      <a class="nav-link" href="/../backend/configuracao/config_1"><?php echo translate("Empresa"); ?></a>
                    </li>
                    <li data-search="<?php echo translate("Avançadas"); ?>">
                      <a class="nav-link" href="/../backend/configuracao/config_3"><?php echo translate("Avançadas"); ?></a>
                    </li>
                    <li data-search="<?php echo translate("Integrações"); ?>">
                      <a class="nav-link" href="/../backend/configuracao/config_4"><?php echo translate("Integrações"); ?></a>
                    </li>
                    <li data-search="<?php echo translate("Calendário"); ?>">
                      <a class="nav-link" href="/../backend/configuracao/config_calendario"><?php echo translate("Calendário"); ?></a>
                    </li>                                      
                  </ul>
                </li>
                <?php endif; ?>

                <li data-search="<?php echo translate("Sair"); ?>">
                  <a class="nav-link" href="/../backend/logout">
                    <i class="fa fa-power-off" aria-hidden="true"></i>
                    <span><?php echo translate("Sair"); ?></span>
                  </a>
                </li>
            
            </ul>

        </nav>
    </div>
    <script>
        // Maintain Scroll Position
        if (typeof localStorage !== 'undefined') {
            if (localStorage.getItem('sidebar-left-position') !== null) {
                var initialPosition = localStorage.getItem('sidebar-left-position'),
                    sidebarLeft = document.querySelector('#sidebar-left .nano-content');
                
                sidebarLeft.scrollTop = initialPosition;
            }
        }
    </script>
    
</div>