<router base="usuario/recuperar">
<?php require_once $_SERVER['DOCUMENT_ROOT'] . '/pagina.segura2.php'; ?>
<?php $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "https") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>
<?php $config = unserialize (CONFIG_DB); ?>

<section class="body-sign">
        
    <div class="center-sign">
        <a href="/backend/" class="logo float-left">
            <img src="/images/config/<?php echo $config[0]['D001_Logosite']; ?>" height="75" alt="<?php echo $config[0]['D001_Empresa']; ?>" />
        </a>

        <div class="panel card-sign">
            <div class="card-title-sign mt-3 text-right">
                <h2 class="title text-uppercase font-weight-bold m-0"><i class="fa fa-user mr-1"></i> <?php echo translate("Recuperar Password"); ?></h2>
            </div>
            <div class="card-body">                             
                <form id="result">
                    <h4><?php echo translate("Digite o seu e-mail abaixo e caso seja válido, enviaremos instruções de reposição de password"); ?>.</h4>  
                    <div class="form-group mb-0">
                        <span id="msn2"></span>
                        <span id="msn3"></span>
                        <input id="validaemail" type="hidden" value="1">
                        <div class="input-group">
                            <input name="email" id="rec_email" type="email" placeholder="<?php echo translate("EMAIL") ?>" class="form-control form-control-lg" />          <span class="input-group-btn">
                                <button id=""Recuperar Password"" class="btn btn-primary btn-lg" type="submit"><?php echo translate("Recuperar"); ?></button>
                            </span>                            
                        </div>
                        <span id="email_error" class="pull-right" style="display:none;"><?php echo translate("Ops! ocorreu um erro"); ?>.</span>
                        <span id="email_success" class="pull-right" style="display:none;"><?php echo translate("Ok! um email foi enviado para confirmação"); ?>. </span>
                        <input type="hidden" id="return_success" value="<?php echo translate("Ok! um email foi enviado para confirmação"); ?>.">
                        <input type="hidden" id="return_erro" value="<?php echo translate("Ops! ocorreu um erro"); ?>.">
                    </div>
                    <p class="text-center mt-3"><?php echo translate("Recordou"); ?>? <a href="/backend"><?php echo translate(LOGIN); ?></a></p>
                    <?php
                        // Cria um objeto com a data atual UTC
                        $dt = new DateTime(gmdate('Y/m/d H:i:s'), new DateTimeZone('UTC'));
                        // Altera a timezone
                        $dt->setTimezone(new DateTimeZone('Europe/Lisbon'));
                        $expires = $dt->format('Y-m-d H:i:s');
                        $unix = strtotime($expires);
                    ?>
                    <input type="hidden" id="token" value="<?php echo $_SERVER['REMOTE_ADDR'].'-'.$unix; ?>">
                </form>
            </div>
        </div>

        <p class="text-center text-muted mt-3 mb-3">&copy; Copyright <?php echo date("Y"); ?>. <?php echo translate("Todos os direitos reservados") ?>.</p>
    </div>
</section>