<router base="usuario/redefinir">
<?php //require_once $_SERVER['DOCUMENT_ROOT'] . '/pagina.segura2.php'; ?>
<?php $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "https") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>
<?php $config = unserialize (CONFIG_DB); ?>

<section class="body-sign">

    <div class="center-sign">
        <a href="/backend/" class="logo float-left">
            <img src="/images/config/<?php echo $config[0]['D001_Logosite']; ?>" height="75" alt="<?php echo $config[0]['D001_Empresa']; ?>" />
        </a>
        
        <div class="panel card-sign">
            <div class="card-title-sign mt-3 text-right">
                <h2 class="title text-uppercase font-weight-bold m-0"><i class="fa fa-user mr-1"></i> Redefinir Password</h2>
            </div>
            <div class="card-body">
                <?php if($dados["session"] == 1): ?>
                <form> 
                    <div class="form-group mb-3">
                        <input type="hidden" id="usu_id" name="usu_id" value="<?php echo $dados["usuario"][0]['usu_id']; ?>">
                        <h3><?php echo $dados["usuario"][0]["usu_nome"]; ?></h3>   
                        <label><?php echo $dados["usuario"][0]["usu_login"]; ?></label>                   
                    </div>
                </form> 
                <form id="return">                    
                    <div class="form-group mb-0">
                        <div class="row">
                            <div class="col-sm-6 mb-3">
                                <label>Password</label>
                                <input name="password" id="usu_password" type="password" class="form-control form-control-lg" />
                                <input id="validasenha" type="hidden" value="1">
                            </div>
                            <div class="col-sm-6 mb-3">
                                <label>Confirmação Password</label>
                                <input name="confirm_password" id="confirm_password" type="password" class="form-control form-control-lg" />
                                <span id="msgSenha"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">    
                        <div class="col-sm-12 text-left">
                            <button id="bt_redefinir" type="submit" class="btn btn-primary mt-2">Redefinir</button>
                        </div>
                    </div>

                    <span id="retorno" class="no-margin-lr margin-15px-top"></span>
                    <span id="ref" class="margin-15px-top"></span>

                    <span class="mt-3 mb-3 line-thru text-center text-uppercase"></span>

                    <input type="hidden" id="password_error" value="OPS! A password não confere.">
                    <input type="hidden" id="password_success" value="Password válido!">    
                    <input type="hidden" id="return_success" value="A password foi alterado com sucesso!">    
            
                </form>

                <?php elseif($dados["session"] == 0 && isset($dados["token"]) == 1 ): ?>
                <div class="col-md-12 col-sm-12 col-xs-12 sm-margin-30px-bottom wow fadeInLeft text-center" style="visibility: visible; animation-name: fadeInLeft; height: 597px;">
                <h4>Ops! O prazo do token expirou.</h4>
                </div>

                <?php elseif($dados["session"] == 0 && isset($dados["token"]) == 0): ?>
                <div class="col-md-12 col-sm-12 col-xs-12 sm-margin-30px-bottom wow fadeInLeft text-center" style="visibility: visible; animation-name: fadeInLeft; height: 597px;">
                <h4>Ops! O prazo do token expirou.</h4>
                </div>

                <?php endif; ?>

            </div>
        </div>
       
        <p class="text-center text-muted mt-3 mb-3">&copy; Copyright <?php echo date("Y"); ?>. Todos os direitos reservados.</p>
    </div>

</section>
