<div>
	<table id="rel_table" width="100%" class="table table-striped table-hover">
		<!-- THEAD -->
		<?php
	    	if(isset($view_status)):

                	if($view_status == 1):

	    ?>    			
	    				<caption>RELATÓRIO EPI ENTRADA   -   <?php echo implode("/", explode("-",$view_dtinicio))." À ".implode("/", explode("-",$view_dtfinal)); ?></caption>	
						<thead style='background-color:#777777; color:#EFEFEF;'>
							<tr>
								<th widht="27%">EPI</th>
								<th widht="3%">TAM</th>
								<th widht="5%">CA</th>
								<th widht="15%">FAB</th>
								<th widht="15%">CAT</th>
								<th widht="10%">NF</th>
								<th widht="5%">QTDE</th>
								<th widht="10%">DATA</th>
								<th widht="10%">STATUS</th>
							</tr>
						</thead>
		<?php 	
	    			elseif($view_status == 2):
	    ?>
						<caption>RELATÓRIO EPI SAÍDA   -   <?php echo implode("/", explode("-",$view_dtinicio))." À ".implode("/", explode("-",$view_dtfinal)); ?></caption>	
	    				<thead style='background-color:#777777; color:#EFEFEF;'>
							<tr>
								<th widht="20%">FUNCIONÁRIO</th>
								<th widht="10%">SETOR</th>
								<th widht="15%">EPI</th>
								<th widht="5%">TAMANHO</th>
								<th widht="5%">CA</th>
								<th widht="10%">FABRICANTE</th>
								<th widht="10%">CATEGORIA</th>
								<th widht="5%">QTDE</th>
								<th widht="10%">DATA</th>
								<th widht="10%">STATUS</th>
							</tr>
						</thead>
		<?php 	
	    			elseif($view_status == 3):
	    ?>
						<caption>RELATÓRIO EPI CATEGORIA   -   <?php echo implode("/", explode("-",$view_dtinicio))." À ".implode("/", explode("-",$view_dtfinal)); ?></caption>	
	    				<thead style='background-color:#777777; color:#EFEFEF;'>
							<tr>
								<th widht="20%">FUNCIONÁRIO</th>
								<th widht="10%">SETOR</th>								
								<th widht="15%">EPI</th>
								<th widht="5%">TAMANHO</th>
								<th widht="5%">CA</th>
								<th widht="8%">FABRICANTE</th>
								<th widht="8%">CATEGORIA</th>
								<th widht="8%">NOTA FISCAL</th>
								<th widht="5%">QTDE</th>
								<th widht="8%">DATA</th>
								<th widht="3%">EST</th>
								<th widht="5%">STATUS</th>
							</tr>
						</thead>
						<script> 
							$(document).ready(function(){
								$('#rel_soma').html("<span>TOTAL ENTRADA: <?php echo $view_relatorio_epi[0]['fluxo_soma'];?></span>  <span>TOTAL SAÍDA: <?php echo $view_relatorio_epi[0]['fluxo_soma1'];?></span>");
							})
						</script>
		<?php 	
	    			elseif($view_status == 4):
	    ?>
						<caption>RELATÓRIO EPI SETOR   -   <?php echo implode("/", explode("-",$view_dtinicio))." À ".implode("/", explode("-",$view_dtfinal)); ?></caption>	
	    				<thead style='background-color:#777777; color:#EFEFEF;'>
							<tr>
								<th widht="20%">FUNCIONÁRIO</th>
								<th widht="10%">SETOR</th>
								<th widht="15%">EPI</th>
								<th widht="5%">TAMANHO</th>
								<th widht="5%">CA</th>
								<th widht="10%">FABRICANTE</th>
								<th widht="10%">CATEGORIA</th>
								<th widht="5%">QTDE</th>
								<th widht="10%">DATA</th>
								<th widht="10%">STATUS</th>
							</tr>
						</thead>
		<?php 	
	    			elseif($view_status == 5):
	    ?>
						<caption>RELATÓRIO EPI FUNCIONÁRIO   -   <?php echo implode("/", explode("-",$view_dtinicio))." À ".implode("/", explode("-",$view_dtfinal)); ?></caption>	
	    				<thead style='background-color:#777777; color:#EFEFEF;'>
							<tr>
								<th widht="20%">FUNCIONÁRIO</th>
								<th widht="10%">SETOR</th>
								<th widht="15%">EPI</th>
								<th widht="5%">TAMANHO</th>
								<th widht="5%">CA</th>
								<th widht="10%">FABRICANTE</th>
								<th widht="10%">CATEGORIA</th>
								<th widht="5%">QTDE</th>
								<th widht="10%">DATA</th>
								<th widht="10%">STATUS</th>
							</tr>
						</thead>
	    <?php 	
	    			endif;
	    	endif;		
	    ?>
		<!-- TBODY -->
    	<?php
	    	if(isset($view_relatorio_epi)):

	    		foreach ($view_relatorio_epi as $relatorio):

	    			switch($relatorio['fluxo_status']):
                    	case '1': $status = "ENTRADA"; $class = "class='fluxo_entreda'"; $fun = " >>>>>>>>>>> "; $nf = $relatorio["fluxo_nf"];  break;
                    	case '2': $status = "SAÍDA";  $class = "class='fluxo_saida'";  $fun = $relatorio["fluxo_funcionario"]; $nf = " ------- "; break;
                	endswitch;

                	/* TAMANHO */

                    if($relatorio['fluxo_tamanho'] == 1): 
                        $tamanho = "P";
                    elseif($relatorio['fluxo_tamanho'] == 2): 
                        $tamanho = "M"; 
                    elseif($relatorio['fluxo_tamanho'] == 3): 
                        $tamanho = "G";
                    elseif($relatorio['fluxo_tamanho'] == 4): 
                        $tamanho = "GG";
                    elseif($relatorio['fluxo_tamanho'] == 5): 
                        $tamanho = "XG";
                    elseif($relatorio['fluxo_tamanho'] > 5): 
                        $tamanho = $relatorio['fluxo_tamanho'];
                    endif;

                    switch($relatorio['fluxo_setor']):
	                    case '0': $setor = " ------- "; break;
	                    case '1': $setor = "Administrativo"; break;
	                    case '2': $setor = "Vendas"; break;
	                    case '3': $setor = "Armazem"; break;
	                    case '4': $setor = "Entrega"; break;
	                    case '5': $setor = "Puxada"; break;
                    endswitch;

                	if($relatorio['fluxo_ident'] == 1)://BUSCA POR ENTRADA
	    ?>    				
			   			<tbody>
							<tr>
								<td><?php echo utf8_encode($relatorio["fluxo_epi"]); ?></td>
								<td><?php echo $tamanho; ?></td>
								<td><?php echo $relatorio["fluxo_ca"]; ?></td>
								<td><?php echo $relatorio["fluxo_fabricante"]; ?></td>
								<td><?php echo $relatorio["fluxo_categoria"]; ?></td>
								<td><?php echo $relatorio["fluxo_nf"]; ?></td>
								<td><?php echo $relatorio["fluxo_qtd"]; ?></td>
								<td><?php echo $relatorio["fluxo_data"]; ?></td>
								<td><?php echo $status; ?></td>
							</tr>
						</tbody>
	    <?php 	
	    			elseif($relatorio['fluxo_ident'] == 2)://BUSCA POR SAÍDA
	    ?>	    			
						<tbody>
							<tr>
								<td><?php echo strtoupper(utf8_encode($relatorio["fluxo_funcionario"])); ?></td>
								<td><?php echo strtoupper($setor); ?></td>
								<td><?php echo strtoupper(utf8_encode($relatorio["fluxo_epi"])); ?></td>
								<td><?php echo $tamanho; ?></td>
								<td><?php echo $relatorio["fluxo_ca"]; ?></td>
								<td><?php echo $relatorio["fluxo_fabricante"]; ?></td>
								<td><?php echo $relatorio["fluxo_categoria"]; ?></td>
								<td><?php echo $relatorio["fluxo_qtd"]; ?></td>
								<td><?php echo $relatorio["fluxo_data"]; ?></td>
								<td><?php echo $status; ?></td>
							</tr>
						</tbody>
		<?php 	
	    			elseif($relatorio['fluxo_ident'] == 3)://BUSCA POR CATEGORIA
	    ?>	    			
						<tbody>
							<tr>
								<td <?php echo $class ?> ><?php echo $fun; ?></td>
								<td <?php echo $class ?> ><?php echo strtoupper($setor); ?></td>
								<td <?php echo $class ?> ><?php echo strtoupper(utf8_encode($relatorio["fluxo_epi"])); ?></td>
								<td <?php echo $class ?> ><?php echo $tamanho; ?></td>
								<td <?php echo $class ?> ><?php echo $relatorio["fluxo_ca"]; ?></td>
								<td <?php echo $class ?> ><?php echo $relatorio["fluxo_fabricante"]; ?></td>
								<td <?php echo $class ?> ><?php echo $relatorio["fluxo_categoria"]; ?></td>
								<td <?php echo $class ?> ><?php echo $nf; ?></td>
								<td <?php echo $class ?> ><?php echo $relatorio["fluxo_qtd"]; ?></td>
								<td <?php echo $class ?> ><?php echo $relatorio["fluxo_data"]; ?></td>
								<td <?php echo $class ?> ><?php echo $relatorio["fluxo_calculo"]; ?></td>
								<td <?php echo $class ?> ><?php echo $status; ?></td>
							</tr>
						</tbody>
		<?php 	
	    			elseif($relatorio['fluxo_ident'] == 4)://BUSCA POR SETOR
	    ?>	    			
						<tbody>
							<tr>
								<td><?php echo strtoupper(utf8_encode($relatorio["fluxo_funcionario"])); ?></td>
								<td><?php echo strtoupper($setor); ?></td>
								<td><?php echo strtoupper(utf8_encode($relatorio["fluxo_epi"])); ?></td>
								<td><?php echo $tamanho; ?></td>
								<td><?php echo $relatorio["fluxo_ca"]; ?></td>
								<td><?php echo $relatorio["fluxo_fabricante"]; ?></td>
								<td><?php echo $relatorio["fluxo_categoria"]; ?></td>
								<td><?php echo $relatorio["fluxo_qtd"]; ?></td>
								<td><?php echo $relatorio["fluxo_data"]; ?></td>
								<td><?php echo $status; ?></td>
							</tr>
						</tbody>
		<?php 	
	    			elseif($relatorio['fluxo_ident'] == 5)://BUSCA POR FUNCIONARIO
	    ?>	    			
						<tbody>
							<tr>
								<td><?php echo strtoupper(utf8_encode($relatorio["fluxo_funcionario"])); ?></td>
								<td><?php echo strtoupper($setor); ?></td>
								<td><?php echo strtoupper(utf8_encode($relatorio["fluxo_epi"])); ?></td>
								<td><?php echo $tamanho; ?></td>
								<td><?php echo $relatorio["fluxo_ca"]; ?></td>
								<td><?php echo $relatorio["fluxo_fabricante"]; ?></td>
								<td><?php echo $relatorio["fluxo_categoria"]; ?></td>
								<td><?php echo $relatorio["fluxo_qtd"]; ?></td>
								<td><?php echo $relatorio["fluxo_data"]; ?></td>
								<td><?php echo $status; ?></td>
							</tr>
						</tbody>
	    <?php 	
	    			endif;
	    		endforeach;

		    	if(empty($view_relatorio_epi)):

		    		echo "<tr>
		    				<td align='center' colspan='12'>Não existe registro!</td>
		    			  </tr>
		    			";

		    	endif;

	    	endif;		
	    ?>

    </table>
</div>