<div class="col-md-12">
  <div class=" titleIdent"> 
      <h2  class="col-md-10">Visualizar Orçamento</h2><span class="closed_acao col-md-2"><i class="pg-close_line pull-right"></i></span>
    <br>
  </div>
  <div class="panel panel-default"> 
    <div class="panel-header">
    <br>
    </div>
    <div class="panel-body">
        <p class="clearfix"></p>
        <div class="row">
          <div class="col-md-12 form-group form-group-default">
            <label for="orc_nome">Nome</label>
            <div class="form-row">
              <span><?php echo $view_orcamento_lista_alt[0]['D010_Nome'] ?></span>
            </div>
          </div>
        </div>        
        <div class="row">
          <div class="col-md-12 form-group form-group-default">
  
          <label for="orc_email">Email</label>
          <div class="form-row">
            <span><?php echo $view_orcamento_lista_alt[0]['D010_Email'] ?></span>
          </div>
          </div>
        </div>
        <div class="row">
           <div class="col-md-6 form-group form-group-default">
              <label for="orc_celular">Celular</label>
              <div class="form-row">
                <span><?php echo $view_orcamento_lista_alt[0]['D010_Celular'] ?></span>
              </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 form-group form-group-default">
  
          <label for="orc_ramo">Pacote</label>
          <div class="form-row">
              <span><?php echo $view_orcamento_lista_alt[0]['D010_Servico']; ?></span>
           </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 form-group form-group-default">
  
            <label for="orc_pdescricao">Descrição</label>
            <div class="form-row">
              <p><?php echo $view_orcamento_lista_alt[0]['D010_Descricao']; ?> </p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 form-group form-group-default">
  
            <label for="orc_pdescricao">Status</label>
            <div class="form-row">
              <p><?php echo $view_orcamento_lista_alt[0]['D010_Status'] ?> </p>
            </div>
          </div>
        </div>
 
      <p class='clearfix'></p>
         
    </div>
  </div>
</div>