<div class="widget-content">
	
   <ul class="mg-folders">
      <li class="<?php echo strpos($_GET["url"], "config_1") != false ? "active" : ""; ?>">
	      <a href="/../backend/configuracao/config_1" class="menu-item" id='tab_empresa'><?php echo translate("EMPRESA"); ?></a>
		</li>
		
		<li class="<?php echo strpos($_GET["url"], "config_3") != false ? "active" : ""; ?>">
      	<a href="/../backend/configuracao/config_3" class="menu-item" id='tab_pg_construcao'><?php echo translate("MANUTENÇÃO"); ?></a>
      </li>
      <!--li class="<?php echo strpos($_GET["url"], "config_2") != false ? "active" : ""; ?>">
   	   <a href="/../backend/configuracao/config_2" class="menu-item" id='tab_avancado'>AVANÇADAS</a>
      </li-->
      
      <li class="<?php echo strpos($_GET["url"], "config_4") != false ? "active" : ""; ?>">
      	<a href="/../backend/configuracao/config_4" class="menu-item" id='tab_pg_integracao'><?php echo translate("INTEGRAÇÕES"); ?></a>
      </li>

      <li class="<?php echo strpos($_GET["url"], "config_calendario") != false ? "active" : ""; ?>">
      	<a href="/../backend/configuracao/config_calendario" class="menu-item" id='tab_pg_integracao'><?php echo translate("CALENDÁRIO"); ?></a>
      </li>


   </ul>
</div>