<!-- Modal Animation -->
<div id="modalAnim" class="zoom-anim-dialog modal-block modal-block-primary">
    <section class="card">
        <header class="card-header">
            <h2 id="modal-title" class="card-title"></h2>
        </header>
        <div class="card-body">
            <div class="modal-wrapper">
                <div class="modal-icon">
                    <i class="fa fa-question-circle"></i>
                </div>
                <div class="modal-text">
                    <p id="modal-body" class="mb-0"></p>
                </div>
            </div>
        </div>
        <footer id="modal-footer" class="card-footer">
            
        </footer>
    </section>
</div>