<style type="text/css">
#tz-title-page-wrapper {
    background: rgb(246, 246, 246) !important;
    margin: 114px 0 35px 0 !important;
}
#tz-about-top-wrapper{
padding: 0px 0 30px !important;
}
</style>

<section id="tz-title-page-wrapper" class=" ">
  <div class="container-fluid">
    <div class="row" id="title-page">
      <div id="tz-position-3" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
        <div class="tz-module module  " id="Mod161">
          <div class="module-inner">
            <div class="module-ct">
              <div class="custom"  >
                <div class="title-br-left container">
                  <center>
                  <h1> <span class="fa fa-exclamation-circle fa-3x"></span> ERROR 404</h1>
                  <h3> OPS! Não foi possível encontrar a página.</h3>
                  </center>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>