</div>



<footer id="footer" style="margin-top:200px!important;">

    <div class="container">

        <div class="row">

            <div class="col-lg-8">

                <h4 class="heading-primary">client.pt</h4>

                <p class="text-color-light">A melhor maneira de manter o controle de seus clientes é ter um software que é capaz não só de permitir a gestão de clientes, bem como fornecer ferramentas que lhe trazem vantagens. CLIENT.PT é um sistema útil de registros de clientes, projetado especificamente para atender às necessidades das rotinas diárias de uma pequena, média ou grande empresa.</p>

                <hr class="light">

            </div>

            <div class="col-lg-3 col-lg-offset-1">

                <h5 class="mb-2">Contactos</h5>

                <span class="phone">+351 912 129 105</span>

                <p class="mb-0 text-color-light" style="color: #c7c7c7">+351 243 704 665</p>

                <ul class="list list-icons list-icons-sm">

                    <li><i class="fa fa-envelope"></i> <a href="mailto:helpdesk@flybizz.net">helpdesk@flybizz.net</a></li>

                </ul>

                <ul class="social-icons">

                    <li class="social-icons-facebook"><a href="https://www.facebook.com/Flybizzwebmarketing" target="_blank" title="Facebook"><i class="fa fa-facebook-f"></i></a></li>

                    <li class="social-icons-twitter"><a href="https://twitter.com/flybizznet" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>

                    <li class="social-icons-linkedin"><a href="https://pt.linkedin.com/in/flybizz" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>

                </ul>

            </div>

        </div>

    </div>  

    <div class="footer-copyright">

        <div class="container text-center text-color-light">

            <a href="/"><?php echo $site_config[0]["D001_Empresa"]; ?></a> &copy; <?php echo date("Y"); ?>. Desenvolvido por:            

            <a class="agencia" href="https://www.flybizz.net">

                <img id="cred" src="/images/flybizz_bco.png" alt="Flybizz Digital Marketing Agency" data-toggle="tooltip" data-placement="top" title="Flybizz Digital Marketing Agency"  height="45" style="margin-right: 25px!important;"/>

            </a>

        </div>

    </div>

</footer>