
     <!--Content Wrapper Start-->
        <div class="content-wrapper">
          <div class="container">
                
                <div class="row section-wrapper">
                  
                    <!--Content Start-->
                    <div class="col-md-8 content-section-body">
                      <div class="box">
                      
                          <!--Archive Title Start-->
                          <div class="archive-title">
                              <h1>Cifras</h1>
                          </div>
                          <!--Archive Title End-->
                          
                          <div class="post-list">
                              
                              <!--Post Entry 1 Start-->
                              <article class="post-type-standard">                         
                                  
                                  <!--Post Entry-->
                                  <div class="post-entry">
                                      <h2>Últimas músicas cifradas por mim...</h2>
                                  </div>                                    
                                  
                              </article>
                              <!--Post Entry 1 End-->


                              <?php if (!empty($site_limit_cifras)):
                                      foreach ($site_limit_cifras as $cifra): ?>

                              <!--Post Entry 2 Start-->
                              <article class="post-blog-list">
                                <div class="blog-list-box">

                                    <!--Post Image-->
                                    <div class="blog-list-img">
                                        <a href="/page/artistas/genero/<?php echo $cifra['D011_Genero'] ?>/artista/<?php echo $cifra['D011_Artista'] ?>">
                                            <figure class="fit-img">
                                                <div class="overlay-hover"></div>
                                                <img src="/images/artista/<?php echo $cifra['D011_Imageminicio'] ?>" alt="<?php echo $cifra['D011_Tags'] ?>" />
                                              </figure>
                                          </a>
                                      </div>                                        
                                                                                  
                                      <!--Post Entry-->
                                      <div class="post-entry">
                                        <div class="blog-list-details">
                                            <h2><a href="/page/cifras/genero/<?php echo $cifra['D011_Genero'] ?>/artista/<?php echo $cifra['D011_Artista'] ?>/cifra/<?php echo $cifra['D011_Chave'] ?>"><?php echo $cifra['D011_Titulo']; ?></a></h2>
                                              <div class="post-description" style="margin: 0 0 -10px !important;">
                                                   Genero: <span><?php echo $cifra['D011_Genero'] ?></span></br>
                                                     Artista: <span><?php echo $cifra['D011_Artista'] ?></span></br>
                                                       Album: <span><?php echo $cifra['D011_Album'] ?></span></br>
                                                         Tom: <span><?php echo $cifra['D011_Codigo'] ?></span></br>
                                              </div>
                                          </div>
                                      </div>

                                      

                                  </div>
                              </article>
                              <!--Post Entry 2 End-->

                              <?php endforeach; 
                                  endif; ?>
                              
                                                             
                          </div>                            
                                                    
                      </div>
                    </div>
                    <!--Content End-->
                    
                    <!--Sidebar Start-->
                    <div class="col-md-4 sidebar-section-body sidebar-sticky">
                        <div class="box">
                            
                            <!--Widget Categories Start-->
                            <aside class="widget widget_categories">
                                <div class="widget-title">
                                    <h3>Categorias</h3>
                                </div>
                                <div class="widget-detail">
                                  <ul>
                                   <?php 
                                      if(!empty($site_menu_lista)):

                                          $arr_master = array();

                                          //print_r($site_menu_count);

                                          foreach ($site_menu_lista as $menu): 

                                          if(array_key_exists($menu['D011_Uid'], $site_menu_count)):

                                            $count = 1;

                                          else:

                                            $count = 0;

                                          endif;

                                          ?>                        

                                          <?php if($count == 0): ?>

                                          <li>
                                            <a href="<?php echo str_replace('|', '/', $menu['D011_Link']); ?>"><?php echo utf8_decode($menu['D011_DescriCategoria']); ?></a>
                                          </li>

                                          <?php else: ?>

                                            <li class="current-menu">
                                              <a><?php echo utf8_decode($menu['D011_DescriCategoria']); ?></a>
                                              <ul>
                                         <?php  endif; ?>

                                          <?php 
                                          if(!empty($site_sub_master)):
                                              foreach ($site_sub_master as $master): 

                                                  if($menu['D011_Uid'] == $master['D011_PertenceCodigoMaster'] && $master['D011_PertenceCodigoSub1'] == 0  && $master['D011_PertenceCodigoSub2'] == 0 && $master['D011_PertenceCodigoSub3'] == 0  && $master['D011_PertenceCodigoSub4'] == 0 && $master['D011_PertenceCodigoSub5'] == 0 ):

                                                  ?>

                                                    <li>
                                                      <a href="<?php echo str_replace('|', '/', $master['D011_Link']); ?>"><?php echo utf8_decode($master['D011_DescriCategoria']); ?></a>
                                                    </li>


                                               <?php  
                                            endif;
                                        endforeach;//submaster
                                    endif; ?>

                                  <?php if($count != 0): echo "</ul></li>"; endif; ?>

                                <?php endforeach;//menu
                                endif; ?>

                                </ul>         

                                </div>
                            </aside>
                            <!--Widget Categories End-->
                            <!--Menu Start-->       
                            
                        </div>
                    </div>
                    <!--Sidebar End-->
                
                </div>
                
                <div class="layout-divider"></div>
                
            </div>
        </div>
        <!--Content Wrapper End-->