<?php require_once $_SERVER['DOCUMENT_ROOT'] . '/pagina.segura2.php'; ?>
<?php $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "https") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>
<section class="page-header-custom-background page-header page-header-center page-header-more-padding page-header-no-title-border" style="background-image: url('/images/config/bg/<?php echo trim($site_config[0]['D001_Imgfundo']); ?>')">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1 style="padding-top: 10px; padding-bottom:10px; padding-right:10px; padding-left:10px; background-color:rgba(25,25,25,0.7);"><strong>PROPRIEDADES</strong></h1>
      </div>
    </div>
  </div>
</section>

<section class="page-header page-header-light page-header-more-padding">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <h1><?php echo str_replace("|", "/", $site_imovel[0]['D011_Titulo']);?><span><?php echo str_replace("|", "/", $site_imovel[0]['D011_Localidade']);?></span></h1>
            </div>            
        </div>
    </div>
</section>

<div class="container">

    <div class="row pb-5 pt-3">
        <div class="col-lg-9">
                    
            <div class="row">
                <div class="col-lg-7">

                    <span class="thumb-info-listing-type thumb-info-listing-type-detail background-color-secondary text-uppercase text-color-light font-weight-semibold p-2 pl-3 pr-3">
                        <?php echo str_replace("|", "/", $site_tipocliente[0]['D011_Titulo']);?>
                    </span>

                    <div class="thumb-gallery">
                        <div class="lightbox" data-plugin-options="{'delegate': 'a', 'type': 'image', 'gallery': {'enabled': true}}">
                            <div class="owl-carousel owl-theme manual thumb-gallery-detail show-nav-hover" id="thumbGalleryDetail">

                                <?php if (!empty($site_imagem)): ?>
                                <?php foreach ($site_imagem as $imagem): ?>
                                                                  
                                <div>
                                    <a href="/images/imovel/<?php echo $imagem['D011_Imovel'] ?>/fotos/<?php echo trim($imagem['D011_Imagem']); ?>">
                                        <span class="thumb-info thumb-info-centered-info thumb-info-no-borders text-4">
                                            <span class="thumb-info-wrapper text-4">
                                                <img alt="Property Detail" src="/images/imovel/<?php echo $imagem['D011_Imovel'] ?>/fotos/<?php echo trim($imagem['D011_Imagem']); ?>" class="img-fluid" alt="<?php echo $imagem['D011_Title'] ?>">
                                                <span class="thumb-info-title text-4">
                                                    <span class="thumb-info-inner text-4"><i class="icon-magnifier icons text-4"></i></span>
                                                </span>
                                            </span>
                                        </span>
                                    </a>
                                </div>

                                <?php endforeach; ?>
                                <?php endif; ?>

                                
                            </div>
                        </div>

                        <div class="owl-carousel owl-theme manual thumb-gallery-thumbs mt" id="thumbGalleryThumbs">

                            <?php if (!empty($site_imagem)): ?>
                            <?php foreach ($site_imagem as $imagem): ?>

                            <div>
                                <img alt="<?php echo $imagem['D011_Title'] ?>" src="/images/imovel/<?php echo $imagem['D011_Imovel'] ?>/fotos/<?php echo trim($imagem['D011_Imagem']); ?>" class="img-fluid cur-pointer">
                            </div>

                            <?php endforeach; ?>
                            <?php endif; ?>
                          
                        </div>
                    </div>

                </div>
                <div class="col-lg-5">
                    
                    <table class="table table-striped">
                        <colgroup>
                            <col width="35%">
                            <col width="65%">
                        </colgroup>
                        <tbody>
                            <tr>
                                <td class="background-color-primary text-light align-middle">
                                    Valor
                                </td>
                                <td class="text-4 font-weight-bold align-middle background-color-primary text-light">
                                   <?php echo number_format($site_imovel[0]['D011_Valor'],0,".",".");?>€
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    REF
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Codigo']);?>
                                </td>
                            </tr>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Condicao'])):
                            ?>
                            <tr>
                                <td>
                                    Condição
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_condicao[0]['D011_Titulo']);?><br>
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Tipo'])):
                            ?>
                            <tr>
                                <td>
                                    Tipo
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_tipo[0]['D011_Titulo']);?><br>
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Tipologia'])):
                            ?>
                            <tr>
                                <td>
                                    Tipologia
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_tipologia[0]['D011_Titulo']);?><br>
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Morada'])):
                            ?>
                            <tr>
                                <td>
                                    Endereço
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Morada']);?><br>
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Localidade'])):
                            ?>
                            <tr>
                                <td>
                                    Localidade
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Localidade']);?>
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Quarto'])):
                            ?>
                            <tr>
                                <td>
                                    Quartos
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Quarto']);?>
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Casabanho'])):
                            ?>
                            <tr>
                                <td>
                                    Casa de banho
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Casabanho']);?>
                                </td>
                            </tr> 
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Salaarea'])):
                            ?>                           
                            <tr>
                                <td>
                                    Sala de estar
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Salaarea']);?> m²
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Area_terreno'])):
                            ?>
                            <tr>
                                <td>
                                    Área do terreno
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Area_terreno']);?> m²
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Construcao'])):
                            ?>
                            <tr>
                                <td>
                                    Ano de Construção
                                </td>
                                <td>
                                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Construcao']);?>
                                </td>
                            </tr>
                            <?php endif; ?>
                            <?php 
                                if(!empty($site_imovel[0]['D011_Energetica'])):
                            ?>
                            <tr>
                                <td>
                                    Certificado energético
                                </td>
                                <td>
                                    <?php 
                                        switch($site_imovel[0]['D011_Energetica']):
                                            case "A+": $vl_energia = "energ_aa"; $txt_energia = "Menos de 25% do consumo de referência"; break;
                                            case "A": $vl_energia = "energ_a"; $txt_energia = "Entre 25% a 50% do consumo de referência"; break;
                                            case "B": $vl_energia = "energ_b"; $txt_energia = "Entre 50% a 75% do consumo de referência"; break;
                                            case "B-": $vl_energia = "energ_b-"; $txt_energia = "Entre 75% a 100% do consumo de referência"; break;
                                            case "C": $vl_energia = "energ_c"; $txt_energia = "Entre 100% a 150% do consumo de referência"; break;
                                            case "D": $vl_energia = "energ_d"; $txt_energia = "Entre 150% a 200% do consumo de referência"; break;
                                            case "E": $vl_energia = "energ_e"; $txt_energia = "Entre 200% a 250% do consumo de referência"; break;
                                            case "F": $vl_energia = "energ_f"; $txt_energia = "Entre 250% a 300% do consumo de referência"; break;
                                            case "G": $vl_energia = "energ_g"; $txt_energia = "Mais de 300% consumo de referência"; break;                                            
                                        endswitch;
                                    ?>
                                    <div class="<?php echo $vl_energia; ?>">
                                        <span><?php echo str_replace("|", "/", $site_imovel[0]['D011_Energetica']);?></span>
                                        <small><?PHP echo $txt_energia; ?></small>
                                    </div>                                    
                                </td>
                            </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>

                </div>
            </div>

            <div class="row">
                <div class="col">
                        <h4 class="mt-3 mb-3">Descrição</h4>
                        <div class="pull-right" style="margin-top:-50px;">                            
                            <ul class="social-icons text-center share pull-right">
                            <li class="social-icons-googleplus"><a href="https://plus.google.com/share?url=<?php echo $actual_link; ?>" onclick="javascript:window.open(this.href,
                    '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><i class="fa fa-google-plus"></i></a></li>
                            <li class="social-icons-facebook" data-href="<?php echo $actual_link; ?>" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $actual_link; ?>&amp;src=sdkpreparse"><i class="fa fa-facebook"></i></a></li>
                            <li class="social-icons-linkedin"><a target="_blank" href="https://www.linkedin.com/shareArticle?mini=true&url=<?php echo $actual_link; ?>&title=<?php echo $site_imovel[0]['D011_Titulo'];?>
                &summary=<?php echo str_replace("|", "/", $site_imovel[0]['D011_Chamada']); ?>&source=LinkedIn"><i class="fa fa-linkedin"></i></a></li>
                            <li class="social-icons-twitter"><a target="_blank" href="https://twitter.com/intent/tweet?text=<?php echo $site_imovel[0]['D011_Titulo'].' - ';?><?php echo str_replace("|", "/", $site_imovel[0]['D011_Chamada']); ?>&url=<?php echo $actual_link; ?>"><i class="fa fa-twitter"></i></a></li>                             </ul>
                            <span style="font-size: 10px;" class="pull-right"><strong style="vertical-align:middle; margin-top:15px; margin-right:10px;">Partilhar : </strong></span>
                        </div>

                    <?php echo str_replace("|", "/", $site_imovel[0]['D011_Descricao']);?>
                   
                    <hr class="solid tall">

                    <h4 class="mt-3 mb-3">Características</h4>

                    <ul class="list list-icons list-secondary row m-0">

                        <?php 
                            if(!empty($site_imovel[0]['D011_Suite'])):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Suite</li>
                        <?php endif; ?>
                        <?php 
                            if(!empty($site_imovel[0]['D011_Garagem'])):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Garagem</li>
                        <?php endif; ?>
                        <?php 
                            if(!empty($site_imovel[0]['D011_Varanda'])):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Varanda</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['	D011_Terraco'])):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Terraço</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Jardim'])):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Jardim</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Cozinha'])):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Cozinha</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Sala'])):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Sala de estar</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['	D011_Casabanho'])):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Casa de banho</li>
                        <?php endif; ?>

                        <?php 
                            if($site_imovel[0]['D011_Piscina'] == true):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Piscina</li>
                        <?php endif; ?>

                        <?php 
                            if($site_imovel[0]['D011_Condominiofechado'] == true):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Condominio fechado</li>
                        <?php endif; ?>

                        <?php 
                            if($site_imovel[0]['D011_Adega'] == true):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Adega</li>
                        <?php endif; ?>
                        <?php 
                            if($site_imovel[0]['D011_Elevador'] == true):
                        ?> 
                            <li class="col-sm-6 col-lg-4"><i class="fa fa-check"></i> Elevador</li>
                        <?php endif; ?>
                        
                    </ul>

                    <hr class="solid tall">

                    <h4 class="mt-3 mb-3">Mais detalhes</h4>

                    <ul class="list list-icons list-secondary row m-0">

                        <?php 
                            if(!empty($site_imovel[0]['D011_Aquecimento'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Aquecimento:</strong> <?php echo $site_imovel[0]['D011_Aquecimento']; ?></li>
                        <?php endif; ?>
                        
                        <?php 
                            if(!empty($site_imovel[0]['D011_Disponibilidade'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Disponibilidade:</strong> <?php echo $site_imovel[0]['D011_Disponibilidade']; ?></li>
                        <?php endif; ?>

                        <?php 
                            if($site_imovel[0]['D011_Piscina'] == true):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Apropriado para pessoa de mobilidade reduzida:</strong> Sim </li>
                        <?php endif; ?>


                        <?php 
                            if(!empty($site_imovel[0]['D011_Area_util'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Área útil:</strong> <?php echo $site_imovel[0]['D011_Area_util']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Area_bruta'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Área bruta:</strong> <?php echo $site_imovel[0]['D011_Area_bruta']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Area_implantacao'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Área de implantação:</strong> <?php echo $site_imovel[0]['D011_Area_implantacao']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Area_terreno'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Área do terreno:</strong> <?php echo $site_imovel[0]['D011_Area_terreno']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if($site_imovel[0]['D011_Vidro'] != false ):
                        ?> 
                        <?php 
                            switch($site_imovel[0]['D011_Vidro']):
                                case "simples": $vl_vidro = "Simples";break;
                                case "duplo": $vl_vidro = "Duplo"; break;
                                case "triplo": $vl_vidro = "Triplo"; break;                            
                            endswitch;
                        ?>
                            <li class="col-sm-12 col-lg-12"><strong>Vídro:</strong> <?php echo $vl_vidro; ?></li>
                        <?php endif; ?>




                        <?php 
                            if(!empty($site_imovel[0]['D011_Suitearea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Suite:</strong> <?php echo $site_imovel[0]['D011_Suitearea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Garagemarea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Garagem:</strong> <?php echo $site_imovel[0]['D011_Garagemarea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Boxarea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Box:</strong> <?php echo $site_imovel[0]['D011_Boxarea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Varandaarea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Varanda:</strong> <?php echo $site_imovel[0]['D011_Varandaarea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Terracoarea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Terraço:</strong> <?php echo $site_imovel[0]['D011_Terracoarea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Jardimarea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Jardim:</strong> <?php echo $site_imovel[0]['D011_Jardimarea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Cozinhaarea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Cozinha:</strong> <?php echo $site_imovel[0]['D011_Cozinhaarea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Salaarea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Sala de estar:</strong> <?php echo $site_imovel[0]['D011_Salaarea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_imovel[0]['D011_Casabanhoarea'])):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Casa de banho:</strong> <?php echo $site_imovel[0]['D011_Casabanhoarea']; ?> m²</li>
                        <?php endif; ?>

                        <?php 
                            if(!empty($site_piso)):
                        ?> 
                            <li class="col-sm-12 col-lg-12"><strong>Piso:</strong> <?php echo $site_piso[0]['D011_Titulo']; ?></li>
                        <?php endif; ?>
                        
                    </ul>

                    <hr class="solid tall">

                    <?php if(!empty($site_imovel[0]['D011_Latitude']) && !empty($site_imovel[0]['D011_Longitude'])): ?>

                    <!-- Google Map js -->
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCnLCpfkI4SEDq5YrCOG-CK_uvs__b313E"></script>
                    <script>
                        function initialize() {
                        var mapOptions = {
                            zoom: 16,
                            scrollwheel: false,
                            center: new google.maps.LatLng(<?php echo $site_imovel[0]['D011_Latitude']; ?>, <?php echo $site_imovel[0]['D011_Longitude']; ?>)
                        };
                        var map = new google.maps.Map(document.getElementById('googlemaps'),
                            mapOptions);
                        var marker = new google.maps.Marker({
                            position: map.getCenter(),
                            animation:google.maps.Animation.BOUNCE,
                            icon: '/images/map-marker.png',
                            map: map
                        });
                        }
                        google.maps.event.addDomListener(window, 'load', initialize);
                    </script>

                    <h4 class="mt-3 mb-3" id="map">Mapa - Localização</h4>
                    <div id="googlemaps" class="google-map m-0 mb-5"></div>

                    <?php endif; ?>

                </div>
            </div>

        </div>
        <div class="col-lg-3">
            <aside class="sidebar">
                <h4 class="pt-0 mb-3 text-color-dark">Pedido de informações</h4>
                <p>Entre em contato conosco ou ligue para solicitar mais informações</p>

                <form id="contactForm" action="" method="POST" class="mb-4">
                    <div class="form-row">
                        <div class="form-group col">
                            <label>Seu nome completo *</label>
                            <input type="text" value="" data-msg-required="Please enter your name." maxlength="100" class="form-control" id="orc_nome" name="orc_nome" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col">
                            <label>Seu endereço de email *</label>
                            <input type="email" value="" data-msg-required="Please enter your email address." data-msg-email="Please enter a valid email address." maxlength="100" class="form-control"id="orc_email" name="orc_email" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col">
                            <label>Seu telefone</label>
                            <input type="text" value="" data-msg-required="Please enter your phone." maxlength="100" class="form-control" id="orc_celular" name="orc_celular" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col">
                            <label>Deixe sua Mensagem aqui... *</label>
                            <textarea maxlength="5000" data-msg-required="Please enter your message." rows="6" class="form-control" name="orc_descricao" id="orc_descricao" required></textarea>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col">
                            <a href="javascript:;" id="bt_orc_cadastrar" name="bt_orc_cadastrar" class="btn btn-primary btn-icon"> Enviar </a>

                            <div class="alert alert-success d-none" id="contactSuccess">
                                Message has been sent to us.
                            </div>

                            <div class="alert alert-danger d-none" id="contactError">
                                Error sending your message.
                            </div>
                        </div>
                    </div>
                </form>

            </aside>
        </div>
    </div>

</div>