<header id="header" data-plugin-options="{'stickyEnabled': false}">

    <div class="header-body">

        <div class="header-top">

            <div class="container">

                <div class="header-row py-2">

                    <div class="header-column justify-content-start">

                        <div class="header-row">

                            <p>

                                <span class="ml-1"><i class="fa fa-phone"></i> <a href="tel:+351912129105">+351 912 129 105</a></span><span class="pl-1"> | <i class="fa fa-envelope"></i> <a href="mailto:helpdesk@flybizz.net"> helpdesk@flybizz.net</a></span>

                            </p>

                        </div>

                    </div>

                    <div class="header-column justify-content-end">

                        <div class="header-row">

                            <ul class="header-social-icons social-icons d-none d-sm-block">

                                <li class="social-icons-facebook"><a href="https://www.facebook.com/Flybizzwebmarketing" target="_blank" title="Facebook"><i class="fa fa-facebook-f"></i></a></li>

                                <li class="social-icons-twitter"><a href="https://twitter.com/flybizznet" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>

                                <li class="social-icons-linkedin"><a href="https://pt.linkedin.com/in/flybizz" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>

                            </ul>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</header>

<div role="main" class="main">

	<div class="container">

		<div class="row mt-5">

			<div class="col text-center">

				<div class="logo">

					<a href="/">

						<img  height="75" src="/images/config/<?php echo $site_config[0]['D001_Logosite'] ?>" alt="Porto">

					</a>

				</div>

			</div>

		</div>

		<div class="row">

			<div class="col">

				<hr class="tall">

			</div>

		</div>

        <div class="row">

            <div class="col text-center">

                <h1 class="mb-2 small">BEM-VINDO</h1>

                <p class="lead">Tenha acesso ao backoffice da sua base de dados.</i></p>

                <a href="../backend/index" class="btn btn-3d btn-primary btn-xl mb-2 mt-4">ENTRAR</a>

            </div>

        </div>

				<!-- 	

        <div class="row">

	        <div class="col">

	            <hr class="tall mt-4">

	        </div>

	    </div> -->

	</div>

</div>