
<section id="cromaheader">
  <!-- <div class="cro_headermask" style=" background: #000000;  opacity: 0.2; "></div> -->
  <h1 class="cro_cust_font" style=" color: #ffffff; ">Ministérios IBI</h1>
</section>

<!-- start tit hthe page layout -->
<section id="pagelayout">
  <div class="row">
    <div id="main">
      <div class="main singlemain cro_pagelayout">    

        <!-- render the page subject to the sidebar settings 1> sidebar left -->
                
          <div class="large-12 column">
            <div class="row">
              

              <section class="cro_frontpage_grs cro_frontpage_layout">
  
                <!-- the loop for the categories -->
                <div class="row">


                      <div class="large-12 column">

                        <div class="cro_grs_grid clearfix">


                          <div class="cro_halfone">

                            <div class="cro_part40 cro_parttop  animated " style="background: #1c1e20;" data-cro-anim-data="fadeInUpBig" data-cro-anim-delay="250">
                                          
                                <div class="cro_grcenter_outer">

                                  <div class="cro_grcenter_inner">
                                    
                                    <h2 style="color: #ffffff;" class="cro_hp_header"><?php echo utf8_decode( $site_ministerio[0]['titulo']); ?></h2>
                                    <p style="color: #ffffff;" class="cro_hp_body"><?php echo utf8_decode( $site_ministerio[0]['chamada']); ?></p>
                                  </div>

                                </div>

                            </div>

                            <div class="cro_part60  animated " data-cro-anim-data="fadeInUpBig" data-cro-anim-delay="300">

                              <div class="cro_part60left"  style="background: url('/qualidade.php?&lar=250&alt=350&imagem=images/artigo/<?php echo $site_ministerio[1]['arquivo']?>') no-repeat center;background-size: cover;" >

                                <div class="cro_gr_labelholder">

                                  <a href="/page/ministerios/link/<?php echo $site_ministerio[1]['chave']; ?>"><?php echo utf8_decode( $site_ministerio[1]['titulo']); ?></a>
                                </div>

                              </div>

                              <div class="cro_part60right  animated " data-cro-anim-data="fadeInUpBig" data-cro-anim-delay="350">

                                <div class="cro_part60rightinner" style="background: url('/qualidade.php?&lar=250&alt=350&imagem=images/artigo/<?php echo $site_ministerio[2]['arquivo']?>') no-repeat center;background-size: cover;">

                                  <div class="cro_gr_labelholder">

                                    <a href="/page/ministerios/link/<?php echo $site_ministerio[2]['chave']; ?>"><?php echo utf8_decode( $site_ministerio[2]['titulo']); ?></a>
                                  </div>

                                </div>

                              </div>


                            </div>


                          </div>

                          <div class="cro_halftwo">

                            <div class="cro_halftwoinner">

                              <div class="cro_part60 cro_parttop  animated " data-cro-anim-data="fadeInUpBig" data-cro-anim-delay="400">


                                <div class="cro_part60left" style="background: url('/qualidade.php?&lar=250&alt=350&imagem=images/artigo/<?php echo $site_ministerio[3]['arquivo']?>') no-repeat center;background-size: cover;">
                                  
                                  <div class="cro_gr_labelholder">

                                    <a href="/page/ministerios/link/<?php echo $site_ministerio[3]['chave']; ?>"><?php echo utf8_decode( $site_ministerio[3]['titulo']); ?></a>
                                  </div>

                                </div>

                                <div class="cro_part60right  animated " data-cro-anim-data="fadeInUpBig" data-cro-anim-delay="450">

                                
                                  <div class="cro_part60rightinner" style="background: url('/qualidade.php?&lar=250&alt=350&imagem=images/artigo/<?php echo $site_ministerio[4]['arquivo']?>') no-repeat center; background-size: cover;">

                                    <div class="cro_gr_labelholder">

                                      <a href="/page/ministerios/link/<?php echo $site_ministerio[4]['chave']; ?>"><?php echo utf8_decode( $site_ministerio[4]['titulo']); ?></a>
                                    </div>

                                  </div>

                                </div>
                                

                              </div>


                              <div class="cro_part40  animated " style="background: #1c1e20;" data-cro-anim-data="fadeInUpBig" data-cro-anim-delay="500">


                                 <div class="cro_grcenter_outer">
                                

                                  <div class="cro_grcenter_inner">

                                    <img src="/images/artigo/<?php echo utf8_decode( $site_ministerio[5]['arquivo']); ?>" alt="">
                                    <h2 style="color: #ffffff;" class="cro_hp_header"><?php echo utf8_decode( $site_ministerio[5]['titulo']); ?></h2>
                                  </div>

                                </div>

                              </div>


                            </div>


                          </div>

                        </div>

                  </div>
                </div>


              </section>



            </div>
          </div>              
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</section>