<?php
if(strpos($_SERVER['REQUEST_URI'], 'index')):
    $urlink = "";
else:
    $urlink = "/../";
endif;
$config = unserialize (CONFIG_DB);
$menuLANGUAGE = unserialize (MENU_LIST);
$menuLINK = unserialize (MENU_LINK);
$languageSIGLA = unserialize (LANGUAGE_SIGLA);
$languageDEFAULT = unserialize (LANGUAGE_DEFAULT);

//$url = explode("/", $_GET["url"]);

?>

<header id="header" class="header-full-width" data-plugin-options="{'stickyEnabled': true, 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyStartAtElement': '#header', 'stickySetTop': '0', 'stickyChangeLogo': false}">
    <div class="header-body">
        <div class="header-container container">
            <div class="header-row">
                <div class="header-column">
                    <div class="header-row">
                        <div class="header-logo my-0">
                            <a href="/">
                                <img alt="<?php echo $config[0]['D001_Empresa']; ?>" width="300" data-sticky-width="300" data-sticky-top="0" src="/images/config/bco/<?php echo $config[0]['D001_Logosite'] ?>" class="pull-left">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="header-column justify-content-center">
            
                    <div class="header-nav justify-content-center p-0">
                        <div class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1">
                            <nav class="collapse">
                                <ul class="nav nav-pills" id="mainNav">
                                    
                                    <?php

                                    if(!empty($menuLANGUAGE)):

                                        //$tt_menu = count($site_menu_lista);
                                        //$metade = floor($tt_menu / 2);

                                        //$arr_master = array();

                                        $num = 0;
                                    
                                        foreach ($menuLANGUAGE as $menu):

                                            $num++;

                                        if(array_key_exists($menu['D008_Uid'], $site_menu_count)):
                                            $count = "menu";
                                        else:
                                            $count = "sub";
                                        endif;

                                        $link = str_replace('|', '/', $menu['D008_Link']); ?>                              
                                        
                                        <?php if($count != "menu"): ?>

                                        <li class="fbz-font-titulo" style="font-size:1.8em!important; letter-spacing: 1px!important;">
                                            <!-- TRATAR DEPOIS POSSIVEL ERRO -->
                                            <?php if($languageDEFAULT[0] == $menu['D008_Idioma']): ?>
                                            <a class="nav-link" href="<?php echo $link; ?>"><?php echo $menu['D008_DescriCategoria']; ?></a>
                                            <?php else: ?>
                                            <a class="nav-link" href="<?php echo '/'.$menu['D008_Idioma'].$link; ?>"><?php echo $menu['D008_DescriCategoria']; ?></a>
                                            <?php endif; ?>
                                        </li>

                                        <?php elseif($count != "sub"): ?>

                                        <li class="dropdown">
                                            <a href="<?php echo $link; ?>" class="dropdown-item dropdown-toggle"><?php echo $menu['D008_DescriCategoria']; ?></a>
                                            <ul class="dropdown-menu">                      
                                        
                                                <?php  endif; ?>

                                                <?php

                                                if(!empty($site_sub_master)):

                                                    foreach ($site_sub_master as $master):

                                                        if($menu['D008_Uid'] == $master['D008_PertenceCodigoMaster'] && $master['D008_PertenceCodigoSub1'] == 0  && $master['D008_PertenceCodigoSub2'] == 0 && $master['D008_PertenceCodigoSub3'] == 0  && $master['D008_PertenceCodigoSub4'] == 0 && $master['D008_PertenceCodigoSub5'] == 0 ):
                                                            ?>

                                                            <li>
                                                                <a class="dropdown-item" href="<?php echo str_replace('|', '/', $master['D008_Link']); ?>"><?php echo $master['D008_DescriCategoria']; ?></a>
                                                            </li>

                                                            <?php
                                                        endif;
                                                    endforeach;//submaster

                                                endif; ?>

                                                <?php if($count != "sub"): echo "</ul></li>"; 

                                                endif; 
                                        endforeach;//menu
                                    endif; ?>                                   
                                </ul>
                            </nav>
                        </div>
                        <?php 
                            $qtd = count($languageSIGLA);
                            $menuLINK;
                           if($qtd > 1):                                                
                        ?>
                        <ul class="linguage">
                            <?php $qtd_lang = 0;                                                       
                            foreach ($languageSIGLA as $sigla): 
                                $qtd_lang++; 
                                if($menuLANGUAGE[0]["D008_Idioma"] == $sigla):
                                    $style = "padding-left: 5px; padding-right: 5px; border: 0.5px solid rgba(250,250,250,0.4);";
                                else:
                                    $style = "";
                                endif;
                                    if($qtd_lang == 1):
                            ?>
                            <li style=" <?php echo $style; ?>" class="list-lang" sigla-lang="<?php echo $sigla; ?>" controller="<?php echo $menuLINK["controller"]; ?>"><a href="javascrpit:;" target="_self"> <?php echo strtoupper($sigla); ?> </a></li> 
                            <?php   else: 
                                                                
                            ?>               
                            <li> | </li>  
                            <li style=" <?php echo $style; ?> " class="list-lang" sigla-lang="<?php echo $sigla; ?>" controller="<?php echo $menuLINK["controller"]; ?>"><a href="javascrpit:;" target="_self"> <?php echo strtoupper($sigla); ?> </a></li>             
                            <?php    
                                endif; 
                            ?>
                                
                            <?php endforeach; ?>
                        </ul>
                        <?php endif; ?>
                        <button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main nav">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</header>



<!-- <header id="header" data-plugin-options="{'stickyEnabled': true, 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyStartAt': 55, 'stickySetTop': '-52px', 'stickyChangeLogo': true}">
    <div class="header-body">
        <div class="header-top" style="background-color: #b25414; border:0px;">
            <div class="container">
                <div class="py-2">
                    <div class="pull-left">
                        <div class="">
                            <p style="color:#FFF!important; font-weight:600;">
                                <span class="ml-1"><i class="fa fa-phone"></i> <?php if(!empty( $site_unidade[0]["D016_Whatsapp"] )): echo "<a href='tel:".str_replace(" ", "", $site_unidade[0]["D016_Whatsapp"])."' style='color:#FFF!important;'>".$site_unidade[0]["D016_Whatsapp"]."</a>"; endif; ?> <?php if(!empty( $site_unidade[0]["D016_Telefone"] )): echo " | <a href='tel:".str_replace(" ", "", $site_unidade[0]["D016_Telefone"])."' style='color:#FFF!important;'>".$site_unidade[0]["D016_Telefone"]."</a>"; endif; ?></span><span class="d-none d-sm-inline-block pl-1"> | <i class="fa fa-envelope"></i>  <a href="mailto:<?php echo $site_unidade[0]["D016_Email"]; ?>" style='color:#FFF!important;'><?php echo $site_unidade[0]["D016_Email"]; ?></a></span>
                            </p>
                        </div>
                    </div>
                    <div class="pull-right">
                        <div class="">
                            <ul class="header-social-icons social-icons d-none d-sm-block">
                                <?php
                                    if(!empty($site_config[0]["D001_Google"])){
                                        echo '<li class="social-icons-google"><a title="googleplus" target="_blank" href="'.str_replace("|", "/", $site_config[0]["D001_Google"]).'"><i class="fa fa-google-plus"></i></a></li>';
                                    }
                                    if(!empty($site_config[0]["D001_Facebook"])){
                                        echo '<li class="social-icons-facebook"><a href="'.str_replace("|", "/", $site_config[0]["D001_Facebook"]).'" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>';
                                    }
                                    if(!empty($site_config[0]["D001_Twitter"])){
                                        echo '<li class="social-icons-twitter"><a href="'.str_replace("|", "/", $site_config[0]["D001_Twitter"]).'" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>';
                                    }
                                    if(!empty($site_config[0]["D001_Youtube"])){
                                        echo '<li class="social-icons-youtube"><a title="YouTube" target="_blank" href="'.str_replace("|", "/", $site_config[0]["D001_Youtube"]).'"><i class="fa fa-youtube-play"></i></a></li>';
                                    }
                                    if(!empty($site_config[0]["D001_Instagram"])){
                                        echo '<li class="social-icons-instagram"><a title="Instagram" target="_blank" href="'.str_replace("|", "/", $site_config[0]["D001_Instagram"]).'" ><i class="fa fa-instagram"></i></a></li>';
                                    }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-container container">
            <div class="header-row">
                <div class="header-column d-block d-xs-block d-sm-block d-md-block d-lg-none">
                    <div class="header-row">
                        <div class="header-logo">
                            <a href="/">
                                
                            </a>
                        </div>
                    </div>
                </div>                 
                <div class="header-column justify-content-end">                            
                    <div class="header-row">
                        <div class="header-nav header-nav-dark-dropdown header-nav-top-line" style="margin-left: 45px;">
                            <div class="header-nav-main header-nav-main-square header-nav-main-effect-3 header-nav-main-sub-effect-1">
                                <nav class="collapse">
                                    
                                </nav>
                            </div>
                            <button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main nav">
                                <i class="fa fa-bars"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header> -->
