<?php $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "https") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>

<section class="page-header-custom-background page-header page-header-center page-header-more-padding page-header-no-title-border" style="background-image: url('/images/config/bg/<?php echo trim($site_config[0]['D001_Imgfundo']); ?>')">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1><strong>NOTÍCIAS</strong></h1>
      </div>
<!--  <div class="col-lg-6">
        <ul class="breadcrumb">
          <li><a href="#">Features</a></li>
          <li class="active">Header Custom Background</li>
        </ul>
      </div> -->
    </div>
  </div>
</section>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <div class="blog-posts single-post">

        
 
        <article class="post post-large blog-single-post">
          <div class="post-image">
            <div class="owl-carousel owl-theme" data-plugin-options="{'items':1}">
              <div>
                <div class="img-thumbnail d-block">
                  <img class="img-fluid" src="/images/noticia/<?php echo $site_noticia[0]['D007_Foto']; ?>" alt="<?php echo $site_noticia[0]['D007_Titulo'];?>">
                </div>
              </div>
            </div>
          </div>
          
          <?php 
          $exp = explode(" ", $site_noticia[0]['D007_Data']);
          $dt = explode("-", $exp[0]);
          switch ($dt[1]):
            case 1: $mes = "Jan"; break;
            case 2: $mes = "Fev"; break;
            case 3: $mes = "Mar"; break;
            case 4: $mes = "Abr"; break;
            case 5: $mes = "Mai"; break;
            case 6: $mes = "Jun"; break;
            case 7: $mes = "Jul"; break;
            case 8: $mes = "Ago"; break;
            case 9: $mes = "Set"; break;
            case 10: $mes = "Out"; break;
            case 11: $mes = "Nov"; break;
            case 12: $mes = "Dez"; break;
          endswitch; 

          ?>

          <div class="post-date">
            <span class="day"><?php echo $dt[2]; ?></span>
            <span class="month"><?php echo $mes; ?></span>
          </div>

          <div class="post-content">

            <h2><a href="javascript:;"><?php echo $site_noticia[0]['D007_Titulo'];?></a></h2>
   
            <?php echo str_replace("|", "/", $site_noticia[0]['D007_Texto']); ?>

          </div>

          <div class="pull-right">
            <span style="font-size: 10px;"><strong>Partilhar : </strong></span>
            <ul class="social-icons text-center share">
              <li class="social-icons-googleplus"><a href="https://plus.google.com/share?url=<?php echo $actual_link; ?>" onclick="javascript:window.open(this.href,
    '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><i class="fa fa-google-plus"></i></a></li>
              <li class="social-icons-facebook" data-href="<?php echo $actual_link; ?>" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $actual_link; ?>&amp;src=sdkpreparse"><i class="fa fa-facebook"></i></a></li>
              <li class="social-icons-linkedin"><a target="_blank" href="https://www.linkedin.com/shareArticle?mini=true&url=<?php echo $actual_link; ?>&title=<?php echo $site_noticia[0]['D007_Titulo'];?>
  &summary=<?php echo str_replace("|", "/", $site_noticia[0]['D007_Chamada']); ?>&source=LinkedIn"><i class="fa fa-linkedin"></i></a></li>
              <li class="social-icons-twitter"><a target="_blank" href="https://twitter.com/intent/tweet?text=<?php echo $site_noticia[0]['D007_Titulo'].' - ';?><?php echo str_replace("|", "/", $site_noticia[0]['D007_Chamada']); ?>&url=<?php echo $actual_link; ?>"><i class="fa fa-twitter"></i></a></li>
              <!-- <li class="social-icons-twitter"><a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php echo $actual_link; ?>" data-via="seuarroba" data-related="seuarroba" data-hashtags="minhaHashtag"> <i class=" fa fa-twitter"></i> </a></li> -->           
            </ul>
          </div>
        </article>

      </div>
    </div>

    <div class="col-lg-3">
      <aside class="sidebar">
               
        <h4 class="heading-primary">Categorias</h4>
        <ul class="nav nav-list flex-column mb-5">
          <li class="nav-item"><a class="nav-link" href="/noticias">Todos</a></li>
          <?php if (!empty($site_cat_noticias)): ?>
            <?php foreach ($site_cat_noticias as $cat): ?>
            <li class="nav-item"><a class="nav-link" href="/noticias/<?php echo $cat['D007_Chave']; ?>"><?php echo $cat['D007_Nome']; ?></a></li>
            <?php endforeach; ?>
          <?php endif; ?>
        </ul>

        <hr>

        <h4 class="heading-primary">Posts Recentes</h4>      
        <ul class="simple-post-list">

          <?php if(!empty($site_last_noticias)): ?>
          <?php foreach ($site_last_noticias as $last_not): 

            $exp1 = explode(" ", $last_not['D007_Data']);
            $dt1 = explode("-", $exp1[0]);
            switch ($dt1[1]):
              case 1: $mes1 = "Jan"; break;
              case 2: $mes1 = "Fev"; break;
              case 3: $mes1 = "Mar"; break;
              case 4: $mes1 = "Abr"; break;
              case 5: $mes1 = "Mai"; break;
              case 6: $mes1 = "Jun"; break;
              case 7: $mes1 = "Jul"; break;
              case 8: $mes1 = "Ago"; break;
              case 9: $mes1 = "Set"; break;
              case 10: $mes1 = "Out"; break;
              case 11: $mes1 = "Nov"; break;
              case 12: $mes1 = "Dez"; break;
            endswitch;  
          ?>

          <li>
            <div class="post-image">
              <div class="img-thumbnail d-block">
                <a href="/noticias/<?php echo $last_not['D007_Categoria']; ?>/<?php echo $last_not['D007_Chave']; ?>">
                  <img src="/images/noticia/<?php echo $last_not['D007_Foto']; ?>" alt="<?php echo $last_not["D007_Titulo"]; ?>" height="55"
                  >
                </a>
              </div>
            </div>
            
            <div class="post-info">

              <a href="/noticias/<?php echo $last_not['D007_Categoria']; ?>/<?php echo $last_not['D007_Chave']; ?>"><?php echo $last_not["D007_Titulo"]; ?></a>
              <div class="post-meta">
                <?php echo $mes1." ".$dt1[2].", ".$dt1[0]; ?>
              </div>
            </div>
          </li>  

        <?php endforeach; ?>
        <?php endif; ?>  

        </ul>
      
      </aside>
    </div>
  </div>

</div>