<?php require_once $_SERVER['DOCUMENT_ROOT'] . '/pagina.segura2.php'; ?>
<?php $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "https") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>

<section class="page-header-custom-background page-header page-header-center page-header-more-padding page-header-no-title-border" style="background-image: url('/images/config/bg/<?php echo trim($site_config[0]['D001_Imgfundo']); ?>')">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1><strong>ORÇAMENTO</strong></h1>
      </div>
<!--  <div class="col-lg-6">
        <ul class="breadcrumb">
          <li><a href="#">Features</a></li>
          <li class="active">Header Custom Background</li>
        </ul>
      </div> -->
    </div>
  </div>
</section>

<!-- START: Partners -->
<div class="nk-box">
    <!-- <div class="bg-image bg-image-parallax op-2" style="background-image: url('assets/images/image-23-a.jpg');"></div> -->
    <!-- <div class="nk-gap-2"></div> -->
    <div class="container">
        <div class="row">          
            <div class="col-lg-12">
                    <h2 class="nk-title">Pedido de informações.</h2>
                    <h5 class="nk-title">Selecione um produto que deseja e preencha o formulário.</h5>                    
                    <form id="contactForm">
                      <div class="form-row">
                        <div class="form-group col-lg-12">
                        <select class="select-menu" id="orc_pacote"  name="orc_pacote" >
                            <option value="0" selected>Selecione aqui</option>
                            <?php foreach ($site_produto as $prod): ?>
                            <option value='<?php echo $prod['D011_Uid'] ?>'><?php echo $prod['D011_DescriCategoria']; ?> </option>
                            <?php endforeach; ?>  
                        </select>
                        </div>
                        <div class="form-group col-lg-6">
                          <label>Nome *</label>
                          <input type="text" value="" data-msg-required="Name" maxlength="100" class="form-control"  id="orc_nome" name="name"  required>
                        </div>
                        <div class="form-group col-lg-6">
                          <label>Email *</label>
                          <input type="email" value="" data-msg-required="Email" data-msg-email="" maxlength="100" class="form-control" name="email" id="orc_email" required>
                        </div>
                      </div>
                      <div class="form-row">
                        <div class="form-group col">
                          <label>Telefone *</label>
                          <input type="text" value="" data-msg-required="Telefone" maxlength="100" class="form-control" name="phone" id="orc_phone" required>
                        </div>
                      </div>
                      <div class="form-row">
                        <div class="form-group col">
                          <label>Mensagem *</label>
                          <textarea maxlength="5000" data-msg-required="Mensagem" rows="10" class="form-control" id="orc_mensagem" name="message"  required></textarea>
                        </div>
                      </div>
                      <div class="form-row">
                        <div class="form-group col">
                          <button id="bt_orc_cadastrar" name="bt_orc_cadastrar" class="btn btn-primary btn-lg">
                              <span>Enviar</span>
                          </button>
                        </div>
                      </div>
                      <small>Nós nunca compartilharemos seu email com ninguém.</small>
                      <div id="retorno" style="margin-top: 20px;"></div>
                      <div id="ref" style="margin-top:20px;"></div>
                    </form>
            </div>
        </div>
    </div>
    <div class="nk-gap-4"></div>
</div>
<!-- END: Partners -->
 