
          <div class="head-title">
            <div class="container-fluid">
                <div class="row">
                    <h2 class="page-title">Portfólio</h2>
                    <div class="breadcrumbs">
                        <ul>
                            <li>Alguns trabalhos realizados</li>
                        </ul>
                    </div>
                    <!-- <p class="title-desc">Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum</p> -->
                </div><!-- end row -->
            </div><!-- end container -->
          </div><!-- end head-title -->

          <section id="portfolio" class="group portfolio-section" style="padding-bottom:50px;">
              <div class="container-fluid">
                  <div class="row no-gutter">
                      <div class="filter">
                          <ul id="options">
                              <li><a data-filter="*" href="#" class="selected">TODOS</a></li>
                              <!-- <li><a data-filter=".outdoor" href="#">Outdoor</a></li>
                              <li><a data-filter=".indoor" href="#">Indoor</a></li>
                              <li><a data-filter=".model" href="#">Model</a></li>
                              <li><a data-filter=".advertisement" href="#">Advertisement</a></li> -->

                              <?php if (!empty($site_menu_lista)): 

                                  $ident = 0;
                                  foreach ($site_menu_lista as $cat):
                                    $ident++;

                                    $linkar = ".".str_replace(" ", "-", $cat['D011_Chave']);
                                    $linkar2 = str_replace(" ", "-", $cat['D011_DescriCategoria']);

                                    if($ident == 1):
                                ?>      

                                  <li><a href="#" data-filter="<?php echo $linkar; ?>"><?php echo $cat['D011_DescriCategoria']; ?></a></li>

                                  <?php else: ?>   
                                  <li><a href="#" data-filter="<?php echo $linkar; ?>"><?php echo $cat['D011_DescriCategoria']; ?></a></li>

                                <?php endif;
                                  endforeach;
                                endif; ?>

                          </ul>
                      </div><!-- end filter -->
                      <div id="foliowrap">

                           <?php if(!empty($site_dados2)): ?>
                            <?php foreach ($site_dados2 as $value): ?>
                           
                            <figure class="foliobox <?php echo $value['D011_Categoria'] ?>">
                              <a href="/page/portfolio/tipo/<?php echo $value['D011_Categoria'];?>/modelo/<?php echo $value['D011_SubCategoria'] ?>/ref/<?php echo $value['D011_Chave'] ?>">
                                <img src="/../qualidade.php?&lar=770&alt=540&imagem=images/portfolio/<?php echo $value['D011_Uid']."/".$value['D011_Imageminicio']; ?>" alt="<?php echo $value['D011_Titulo']; ?>">
                              
                                <figcaption>
                                    <span class="folcat"><?php echo $value['D011_Titulo']; ?></span>
                                    <h3 class="foltitle"><?php echo $value['D011_Categoria'] ?></h3>
                                </figcaption>
                              </a>
                            </figure><!-- end foliobox -->

                          <?php endforeach ?>
                          <?php endif; ?>  

                                      

                      </div><!-- folio-wrap -->
                  </div><!-- end row -->
                  <div class="row">
                    <div class="paging-wrap" style="text-align:center;">
                            <?php 
                        if(!empty($site_portfolios)):

                           $info['pagination']['reg_final'] =  $site_portfolios['reg_final'];
                           $info['pagination']['n_paginas'] =  $site_portfolios['n_paginas'];
                           $info['pagination']['pg_atual'] =  $site_portfolios['pg_atual'];
                           $info['pagination']['pg_anterior'] =  $site_portfolios['pg_anterior'];
                           $info['pagination']['pg_proxima'] =  $site_portfolios['pg_proxima'];
                           $info['pagination']['lnk_impressos'] =  $site_portfolios['lnk_impressos'];
                           $info['pagination']['finalpag'] =  $site_portfolios['finalpag'];
                           $info['pagination']['arquivo'] =  $site_portfolios['arquivo'];
                           $info['pagination']['pag'] =  $site_portfolios['pag'];
                           $info['pagination']['nlinks'] =  $site_portfolios['nlinks'];
                           $info['pagination']['temp'] =  $site_portfolios['temp'];
                           $info['pagination']['totreg'] =  $site_portfolios['totreg'];

                        else:

                           $info['pagination']['reg_final'] =  0;
                           $info['pagination']['n_paginas'] =  0;
                           $info['pagination']['pg_atual'] =  0;
                           $info['pagination']['pg_anterior'] =  0;
                           $info['pagination']['pg_proxima'] =  0;
                           $info['pagination']['lnk_impressos'] =  0;
                           $info['pagination']['finalpag'] =  0;
                           $info['pagination']['arquivo'] =  0;
                           $info['pagination']['pag'] =  0;
                           $info['pagination']['nlinks'] =  0;
                           $info['pagination']['temp'] =  0;
                           $info['pagination']['totreg'] =  0;

                        endif;

                          navipages($home=1,$center=1,$info); 


                         function navipages($home=0,$center=0, array $info)
                        {

                           $reg_final = $info['pagination']['reg_final'];
                           $n_paginas =  $info['pagination']['n_paginas'];         
                           $pg_atual =  $info['pagination']['pg_atual'];
                           $pg_anterior =  $info['pagination']['pg_anterior'];
                           $pg_proxima =  $info['pagination']['pg_proxima'];
                           $lnk_impressos =  $info['pagination']['lnk_impressos'];
                           $finalpag =  $info['pagination']['finalpag'];
                           $arquivo =  $info['pagination']['arquivo'];
                           $pag =  $info['pagination']['pag'];
                           $nlinks =  $info['pagination']['nlinks'];
                           $temp =  $info['pagination']['temp'];
                           $totreg =  $info['pagination']['totreg'];

                          // global $pg_atual, 
                          // $pg_anterior,
                          // $pg_proxima,  
                          // $n_paginas, 
                          // $reg_final, 
                          // $totreg, 
                          // $temp, 
                          // $nlinks,       
                          // $lnk_impressos,        
                          // $arquivo, 
                          // $pag,
                          // $urlhomepage,
                          // $finalpag,
                          // $barborder;
                          ?>
                          <?php 
                          if($n_paginas > 1){ ?>

                                    <ul class="pagination pagination-sm">
                                      <!--li><a href="<?php echo $arquivo; ?>/1"><i class="icofont icofont-rounded-left" aria-hidden="true"></i></a></li-->
                                      <?php if (isset($pag) && $pag > 1){ ?>
                                      <li><a href="<?php echo $arquivo; ?>/<?php echo $pg_anterior; ?>"><i class="icofont icofont-rounded-left" aria-hidden="true"></i></a></li>                                      
                                      <?php } ?>
                                      <?php
                                                  if ($temp >= $nlinks)
                                                  {
                                                  if ($n_paginas > $nlinks) 
                                                  {
                                                  $n_maxlnk = $temp + 4;
                                                  $nlinks   = $n_maxlnk;
                                                  $n_start  = $temp - 6;
                                                  if($n_start==-1)
                                                  {
                                                  $n_start=0;
                                                  }
                                                  $lnk_impressos = $n_start;
                                                  }
                                                  }
                                                  while(($lnk_impressos < $n_paginas) and ($lnk_impressos < $nlinks))
                                                  { 
                                                  $lnk_impressos ++;
                                                  ?>
                                      <?php
                                                  if ($pg_atual != $lnk_impressos)
                                                  {
                                                  echo "<li><a href=\"$arquivo/$lnk_impressos\">";
                                                  }
                                                  if ($pg_atual == $lnk_impressos)
                                                  {
                                                  echo "<li class=\"active\"><a href=\"javascript:;\">$lnk_impressos  <span class=\"sr-only\">(current)</span></a></li>";
                                                  } 
                                                  else 
                                                  {
                                                  echo "$lnk_impressos"."</li>";
                                                  }
                                                  ?>
                                      </a>
                                      <?php
                                                  }
                                                  ?>
                                      <?php
                                                  if ($reg_final < $totreg) 
                                                  {
                                                  ?>
                                      <li><a href="<?php echo $arquivo; ?>/<?php echo $pg_proxima; ?>"><i class="icofont icofont-rounded-right" aria-hidden="true"></i></a></li>
                                      <?php
                                                  } 
                                                  ?>
                                      <!--li><a href="<?php echo $arquivo; ?>/<?php echo $finalpag; ?>"><i class="icofont icofont-rounded-right" aria-hidden="true"></i> </a></li--!>
                                    </ul>

                          <?php }} ?> 
                    </div>


                  </div>
              </div><!-- end container -->
          </section><!-- cd-section -->                       