
<section class="row final-inner-header">
  <div class="container">
    <h2 class="this-title">Serviços</h2>
  </div>
 </section>
 <section class="row final-breadcrumb">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li><a href="/servicos">Serviços</a></li>
      <li class="active"><?php echo strip_tags($site_servico[0]['D011_Titulo']); ?></li>
    </ol>
  </div>
 </section>

<section class="clearfix news-wrapper">
  <div class="container clearfix common-pad-room1">
    <div class="row">
        


        <div class="family-outer">
          
          <div class="col-lg-5 col-md-5 col-xs-12 pull-left family-content">
            <h2><?php echo strip_tags($site_servico[0]['D011_Titulo']); ?></h2>
            <?php echo str_replace("|", "/", $site_servico[0]['D011_Descricao']); ?>



          </div> 


          <div id="gallery" class="col-lg-7 col-md-7 col-xs-12 pull-right family-img family-img-page gallery-page-one">

              
                  <div class="image-gallery" data-filter-class="gallery-sorter">


                    <?php if (!empty($site_foto)): ?>
                      <?php foreach ($site_foto as $foto): ?>

                          <div class="single-gallery anim-5-all bedroom interoors roof drawing masonryImage mix span-4">
                            <div class="img-holder hover">
                              <img src="/images/servico/<?php echo $site_servico[0]['D011_Uid'] ?>/<?php echo $foto['D011_Imagem']; ?>" alt="">
                              <div class="content">
                                <div class="link-gallery">
                                  <div class="media-right">
                                    <a  rel="help" data-imagelightbox="g" href="/images/servico/<?php echo $site_servico[0]['D011_Uid'] ?>/<?php echo $foto['D011_Imagem']; ?>">
                                      <i class="icon icon-DSLRCamera"></i>
                                    </a> 
                                  </div>
                                </div>              
                              </div>
                            </div>
                            
                          </div><!-- /.single-gallery -->
                        
                      <?php endforeach; ?>
                    <?php endif; ?>

                
                  </div><!-- /.image-gallery -->
           
            
             <a href="/servicos/cat/all/p/0" class=" btn btn-danger pull-right" style="margin-top: 30px;
             margin-bottom: 30px;">Voltar para Serviços</a> 
            
          </div>


          



        </div>  
         
    
         
         
         
      </div>
     
    </div>
  </section>   
<!-- Family Fun style-->