
    <!-- heading-banner start -->

    <div class="heading-banner">

      <div class="container">

        <div class="row">

          <div class="col-lg-12">

            <div class="heading-banner-title">

              <h2>Vídeos</h2>

            </div>

          </div>

        </div>

      </div>

    </div>

    <!-- heading-banner end -->

    <!-- shop-area start -->

    <div class="blog-area">

      <div class="container">

        <div class="row">

          <!-- shop-content start -->

          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

            <?php 

              if(!empty($site_video)):

                foreach ($site_video as $video): 

                  $exp = explode(" ", $video['D014_Data']);

                  $dt = explode("-", $exp[0]);

                  switch ($dt[1]):

                    case 1: $mes = "JAN"; break;

                    case 2: $mes = "FEV"; break;

                    case 3: $mes = "MAR"; break;

                    case 4: $mes = "ABR"; break;

                    case 5: $mes = "MAI"; break;

                    case 6: $mes = "JUN"; break;

                    case 7: $mes = "JUL"; break;

                    case 8: $mes = "AGO"; break;

                    case 9: $mes = "SET"; break;

                    case 10: $mes = "OUT"; break;

                    case 11: $mes = "NOV"; break;

                    case 12: $mes = "DEZ"; break;

                  endswitch;    

                  ?>

            <!-- single-latest-blog start -->

            <div class="single-latest-blog pad-bottom">

              <h3><a href="/page/video/link/<?php echo $video['D014_Chave']; ?>"><?php echo $video['D014_Titulo'];?></a></h3>

              <div class="latest-blog-img embed-responsive embed-responsive-16by9">
                <?php if($video['D014_Categoria'] == 1 ): //YOUTUBE ?>

                  <iframe width="1080" height="608" src="https://www.youtube.com/embed/<?php echo str_replace("|", "/", $video['D014_Arquivourl']);?>" frameborder="0" allowfullscreen></iframe>              

                <?php else: ?>

                  <iframe src="<?php echo str_replace("|", "/", $video['D014_Arquivourl']);?>" width="1080" height="608" frameborder="0" title="<?php echo str_replace("|", "/", $video['D014_Titulo']);?>" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

                <?php endif; ?>
              </div>

              <div class="latest-blog-content">                

                <div class="meta">

                  <span class="time"><i class="fa fa-calendar"></i> <?php echo $dt[2]." ".$mes." ".$dt[0]; ?></span>

                </div>

                <p><?php echo str_replace("|", "/", $video['D014_Descricao']);?></p>

              </div>

            </div>

            <!-- single-latest-blog end -->


            <?php                                      

                endforeach;

              endif; 

            ?>

            <!-- single-latest-blog end -->           

            <div class="shop-pagination">

              <p class="clearfix"></p>

              <a href="/../page/videos/p/0" class=" btn btn-danger pull-right">Voltar para Vídeos</a>

              <p class="clearfix"></p>

            </div>          

          </div>

          <!-- shop-content end -->

        </div>

      </div>

    </div>  

    <!-- shop-area end -->