       
<div class="col-lg-12" style="padding-top: 20px;">

    <h4 style="padding-top: 20px;"><i class="fa fa-pencil-square-o"></i> ALTERAR DADOS CLIENTE</h4>
    <h5><i class="fa fa-arrow-right"></i> DADOS PESSOAIS</h5>
    <?php if(isset($site_cliente_lista)): ?>
    <?php foreach ($site_cliente_lista as $cli): ?>
    <div class="form-group">
        <label for="cli_nome_alt">Nome</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_nome_alt" value="<?php echo $cli['cli_nome'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div> 
    <div class="form-group">
        <label for="cli_cpf_alt">CPF</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_cpf_alt" value="<?php echo $cli['cli_cpf'];?>" placeholder="Nome" disabled>
            <div class="input-group-addon"></div>
        </div>
    </div> 
    <div class="form-group">
        <label for="cli_email_alt">Email</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_email_alt" value="<?php echo $cli['cli_email'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div> 
    <div class="form-group">
        <label for="cli_telefone_alt">Telefone</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_telefone_alt" value="<?php echo $cli['cli_telefone'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div> 
    <div class="form-group">
        <label for="cli_telefone2_alt">Telefone2</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_telefone2_alt" value="<?php echo $cli['cli_telefone2'];?>" placeholder="Nome">
            <div class="input-group-addon"></div>
        </div>
    </div> 
    <div class="form-group">
        <label for="cli_celular_alt">Celular</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_celular_alt" value="<?php echo $cli['cli_celular'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div> 
    <h4><i class="fa fa-arrow-right"></i> DADOS ENTREGA</h4>
    <div class="form-group">
        <label for="cli_endereco_alt">Endereço</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_endereco_alt" value="<?php echo $cli['cli_endereco'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div>
    <div class="form-group">
        <label for="cli_endereco_alt">Número</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_numero_alt" value="<?php echo $cli['cli_numero'];?>" placeholder="Número" required>
            <div class="input-group-addon"></div>
        </div>
    </div>
    <div class="form-group">
        <label for="cli_bairro_alt">Bairro</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_bairro_alt" value="<?php echo $cli['cli_bairro'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div>
    <div class="form-group">
        <label for="cli_cidade_alt">Cidade</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_cidade_alt" value="<?php echo $cli['cli_cidade'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div>
    <div class="form-group">
        <label for="cli_uf_alt">UF</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_uf_alt" value="<?php echo $cli['cli_uf'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div> 
    <div class="form-group">
        <label for="cli_cep_alt">CEP</label>
        <div class="input-group">  
            <input type="text" class="form-control" id="cli_cep_alt" value="<?php echo $cli['cli_cep'];?>" placeholder="Nome" required>
            <div class="input-group-addon"></div>
        </div>
    </div> 
    <?php endforeach ?>
    <?php endif; ?> 
    <button name="bt_cancelar" id="bt_cancelar" class="btn btn-default pull-left" >Cancelar</button>
    <button name="bt_alterar" id="bt_alterar" class="btn btn-default pull-right">Alterar</button>
    <span id="retorno"></span>   
    <div id="ref"></div>
</div>   
