<!-- Page Header -->
<div class="page-header bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <!-- Page Header Wrapper -->
                <div class="page-header-wrapper">
                    <!-- Title & Sub Title -->
                    <h3 class="title">Meus Pedidos</h3>
                    <!-- <h6 class="sub-title">All you want know</h6> -->
                    <ol class="breadcrumb">
                        <li><a href="index.html">Home</a></li>
                        <li class="active">Meus Pedidos</li>
                    </ol><!-- Breadcrumb -->
                </div><!-- Page Header Wrapper -->
            </div><!-- Coloumn -->
        </div><!-- Row -->
    </div><!-- Container -->
</div><!-- Page Header -->

  <!-- Page Main -->
<div role="main" class="main">
    <!-- Section -->
    <section class="bg-lgrey">  
        <div class="container">


            <div class="row">         
                <div class="col-lg-12 ">     
                    <div class="box_carrinho">

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Pedido</th>
                                    <!-- <th>Produto</th> -->
                                    <th>Itens</th>
                                    <th>Data</th>
                                    <th>Valor</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(isset($site_pedido_lista)): ?>
                                    <?php foreach ($site_pedido_lista as $ped): ?>
                                        <tr>
                                            <td><?php echo str_pad($ped['ped_numero'], 6, "0", STR_PAD_LEFT);?></td>
                                            <!-- <td><?php echo $ped['cur_titulo'];?></td> -->
                                            <td><?php echo $ped['ped_item'];?></td>
                                            <td><?php $dt = date_create($ped['ped_data']); echo date_format($dt,"d/m/Y H:i"); ?></td>
                                            <td>R$ <?php echo number_format($ped['ped_total'],2,",",".")?></td>
                                            <td>
                                                <?php                                         
                                                    echo '<span class=""><b>'.$ped['ped_status'].'</b></span>';
                                                ?>
                                            </td>
                                            <td>
                                                <input type="hidden" value="<?php echo $ped['ped_id'] ?>" />
                                                <a id="pView" class="pedTitle" data-original-title="Ver Pedido"><i id="peview" class="icon-search"></i><span> Ver Pedido</span></a>
                                            </td>
                                        </tr>
                                    <?php endforeach ?>
                                <?php else: ?>
                                    <tr>
                                        <td>OPS! nunhum pedido ainda. </td>
                                    </tr>
                                <?php endif; ?>                  
                            </tbody>
                            <tfoot>                  
                            </tfoot>
                        </table>
                       
                    </div> 
                </div>   
            </div>



        </div><!-- Container -->    
    </section><!-- Section -->  
    
  
</div><!-- Page Main 